-- Seed additional motivational quotes
WITH new_quotes AS (
  SELECT * FROM (
    VALUES
      ('Nunca reclame. Nunca explique. Mantenha a mente afiada e a boca fechada.', 'Thomas Shelby', 'mindset'),
    ('Eu não jogo o jogo. Eu mudo as regras.', 'Harvey Specter', 'mindset'),
    ('O talento sem trabalho duro não é nada.', 'Cristiano Ronaldo', 'mindset'),
    ('Se você acha que está no limite, ainda tem 60% de força para usar.', 'David Goggins', 'mindset'),
    ('Sem ação, a melhor intenção do mundo é só lixo.', 'Jordan Belfort', 'mindset'),
    ('A disciplina é a ponte entre o plano e o resultado.', 'Ruyter', 'mindset'),
    ('Não confunda silêncio com fraqueza. É planejamento.', 'Thomas Shelby', 'mindset'),
    ('Ganhar é melhor do que ser justo. Mas ganhar sendo justo é invencível.', 'Harvey Specter', 'mindset'),
    ('Foco, disciplina e sacrifício. Repita até vencer.', 'Cristiano Ronaldo', 'mindset'),
    ('Pare de procurar motivação. Seja o motivo.', 'David Goggins', 'mindset'),
    ('Se você me der 5 segundos, vendo qualquer coisa. Porque eu acredito nela.', 'Jordan Belfort', 'mindset'),
    ('O mundo não vai te recompensar por ser bom. Vai te testar por ser forte.', 'Ruyter', 'mindset'),
    ('A guerra interna é diária. Quem não luta, afunda.', 'Thomas Shelby', 'mindset'),
    ('Trabalhe duro em silêncio. O sucesso vai gritar por você.', 'Harvey Specter', 'mindset'),
    ('Eu treino como se fosse o último treino da minha vida. Todos os dias.', 'Cristiano Ronaldo', 'mindset'),
    ('O conforto é um veneno disfarçado de recompensa.', 'David Goggins', 'mindset'),
    ('A única coisa entre você e seu objetivo é a desculpa que você conta.', 'Jordan Belfort', 'mindset'),
    ('Homem de verdade não espera momento certo. Ele cria.', 'Ruyter', 'mindset'),
    ('Seja calmo como uma bomba armada.', 'Thomas Shelby', 'mindset'),
    ('Você não precisa de sorte. Você precisa de postura.', 'Harvey Specter', 'mindset'),
    ('Você precisa querer vencer mais do que odeia perder.', 'Cristiano Ronaldo', 'mindset'),
    ('Você vai quebrar. A pergunta é: você levanta ou desiste?', 'David Goggins', 'mindset'),
    ('Pare de esperar. Comece a agir como se já tivesse chegado lá.', 'Jordan Belfort', 'mindset'),
    ('O tempo não cura nada. Ele só expõe quem não fez nada.', 'Ruyter', 'mindset'),
    ('Se tiver que sangrar pra vencer, sangre sorrindo.', 'Thomas Shelby', 'mindset'),
    ('Não me desafie. Eu já ia vencer sem você.', 'Harvey Specter', 'mindset'),
    ('É você contra você. Sempre foi.', 'Cristiano Ronaldo', 'mindset'),
    ('A mente vai te sabotar. Treine para ignorar.', 'David Goggins', 'mindset'),
    ('Venda para si mesmo primeiro. Depois venda para o mundo.', 'Jordan Belfort', 'mindset'),
    ('Se a rotina não muda o homem, ela mata o espírito.', 'Ruyter', 'mindset'),
    ('Uma atitude decidida derruba muralhas.', 'Thomas Shelby', 'mindset'),
    ('Não aceito não como final.', 'Harvey Specter', 'mindset'),
    ('Dor hoje é orgulho de amanhã.', 'Cristiano Ronaldo', 'mindset'),
    ('Você acha que fracassou? Então você ainda não tentou.', 'David Goggins', 'mindset'),
    ('Ambição não é crime. É força.', 'Jordan Belfort', 'mindset'),
    ('O medo existe para treinar sua coragem.', 'Ruyter', 'mindset'),
    ('Não confie nos aplausos. Confie no suor.', 'Thomas Shelby', 'mindset'),
    ('Destaque-se ou desapareça.', 'Harvey Specter', 'mindset'),
    ('Treino quando ninguém vê. Sucesso quando todos notam.', 'Cristiano Ronaldo', 'mindset'),
    ('Dor é temporária. Orgulho é eterno.', 'David Goggins', 'mindset'),
    ('Pensar grande é obrigação.', 'Jordan Belfort', 'mindset'),
    ('Você é o herói da sua própria batalha.', 'Ruyter', 'mindset'),
    ('O silêncio também comunica. Escolha o certo.', 'Thomas Shelby', 'mindset'),
    ('Comando de si mesmo ou servo das circunstâncias.', 'Harvey Specter', 'mindset'),
    ('Transforme pressões em combustível.', 'Cristiano Ronaldo', 'mindset'),
    ('Quando cansar, lembre por que começou.', 'David Goggins', 'mindset'),
    ('Sonho pequeno gera vida medíocre.', 'Jordan Belfort', 'mindset'),
    ('A vitória respeita quem não desiste.', 'Ruyter', 'mindset'),
    ('O respeito se conquista na origem das ações.', 'Thomas Shelby', 'mindset'),
    ('Você define seu padrão. O resto corre atrás.', 'Harvey Specter', 'mindset'),
    ('Cada treino é uma promessa de superação.', 'Cristiano Ronaldo', 'mindset'),
    ('Aceite a dor. Ela é sua aliada.', 'David Goggins', 'mindset'),
    ('Coloque o medo para trabalhar pra você, não contra você.', 'Jordan Belfort', 'mindset'),
    ('Estruture sua mente antes de construir seu mundo.', 'Ruyter', 'mindset'),
    ('Quem controla o medo controla o destino.', 'Thomas Shelby', 'mindset'),
    ('Nunca se desculpe por ambição.', 'Harvey Specter', 'mindset'),
    ('O impossível é só opinião de quem desistiu.', 'Cristiano Ronaldo', 'mindset'),
    ('Reivindique seu poder mental todos os dias.', 'David Goggins', 'mindset'),
    ('Você atrai o que acredita. Acredite grande.', 'Jordan Belfort', 'mindset'),
    ('O conforto dilui a esperança.', 'Ruyter', 'mindset'),
    ('Planos sem execução são fantasias.', 'Thomas Shelby', 'mindset'),
    ('Competir é viver. Aceitar menos que ganhar é morrer aos poucos.', 'Harvey Specter', 'mindset'),
    ('Vontade supera talento quando o talento não quer suar.', 'Cristiano Ronaldo', 'mindset'),
    ('As cicatrizes são medalhas da sua resistência.', 'David Goggins', 'mindset'),
    ('Seja tão bom que não ignorem sua presença.', 'Jordan Belfort', 'mindset'),
    ('A mente forte domina o caos.', 'Ruyter', 'mindset'),
    ('Cada dia é batalha. Vença um dia de cada vez.', 'Thomas Shelby', 'mindset'),
    ('Não espere convite. Crie seu espaço.', 'Harvey Specter', 'mindset'),
    ('Gols não me definem, mas a jornada sim.', 'Cristiano Ronaldo', 'mindset'),
    ('Você vai suar. Vai doer. Vai valer.', 'David Goggins', 'mindset'),
    ('Carisma sem caráter não constrói império.', 'Jordan Belfort', 'mindset'),
    ('Pequenas vitórias constroem gigantes.', 'Ruyter', 'mindset'),
    ('Vingança? Não. Transformação.', 'Thomas Shelby', 'mindset'),
    ('O controle que você toma define sua vida.', 'Harvey Specter', 'mindset'),
    ('Não importa quem você é, importa quem você quer ser.', 'Cristiano Ronaldo', 'mindset'),
    ('Limites são ilusões mentais.', 'David Goggins', 'mindset'),
    ('Venda seu sonho. Faça ele irresistível.', 'Jordan Belfort', 'mindset'),
    ('Sentir medo não é falha — não agir por ele sim.', 'Ruyter', 'mindset'),
    ('Ainda que a tempestade venha, a paz está dentro de você.', 'Thomas Shelby', 'mindset'),
    ('Magnificência é aceitar seu valor sem pedir permissão.', 'Harvey Specter', 'mindset'),
    ('Disciplina é amor por si mesmo em forma de ação.', 'Cristiano Ronaldo', 'mindset'),
    ('Acorde com fome, durma com propósito.', 'David Goggins', 'mindset'),
    ('Poder real aparece quando você decide não depender de aplausos.', 'Jordan Belfort', 'mindset'),
    ('Seja fonte da sua própria autoridade.', 'Ruyter', 'mindset'),
    ('Cada cicatriz conta uma história de vitória.', 'Thomas Shelby', 'mindset'),
    ('Seja mestre da sua sombra, não refém dos seus medos.', 'Harvey Specter', 'mindset'),
    ('Quando sua mente manda parar, sua ambição diz: continua.', 'Cristiano Ronaldo', 'mindset'),
    ('Ultrapasse a dor. Ela encontra fraqueza, você encontra força.', 'David Goggins', 'mindset'),
    ('Construa legado no silêncio dos seus esforços.', 'Jordan Belfort', 'mindset'),
    ('Transforme suor em som. Deixe o mundo escutar sua presença.', 'Ruyter', 'mindset')
  ) AS v(text, author, category)
)
INSERT INTO public.quotes (text, author, category)
SELECT v.text, v.author, v.category
FROM new_quotes v
WHERE NOT EXISTS (
  SELECT 1 FROM public.quotes existing
  WHERE existing.text = v.text
    AND existing.author = v.author
);
