-- ============================================
-- SEED: Focus Protocol L2 — "Aprendizado Acelerado"
-- ============================================
-- NOTE: The journeys row for 'focus-protocol-l2' already exists
-- from 20260218000001_seed_digital_detox_l1.sql.
-- This migration seeds phases, days, and habit templates only.
-- Base habits from L1 (deep_work_session, focus_mode, daily_task_1,
-- bedtime_tracking, phone_free_block, focused_reading, time_blocking,
-- active_recall, spaced_repetition, weekly_focus_review) are NOT
-- re-seeded — they carry over from focus-protocol-l1.

DO $$
DECLARE
  v_journey_id uuid;
  v_phase1_id uuid;
  v_phase2_id uuid;
  v_phase3_id uuid;
  v_phase4_id uuid;
BEGIN
  SELECT id INTO v_journey_id FROM public.journeys WHERE slug = 'focus-protocol-l2';

  -- ============================================
  -- 1. Phases
  -- ============================================

  INSERT INTO public.journey_phases (journey_id, phase_number, title, subtitle, description, day_start, day_end, badge_illustration_key, badge_name)
  VALUES (v_journey_id, 1, 'MEMÓRIA', 'Seu cérebro é mais poderoso do que imagina', E'Técnica Feynman, leitura ativa, palácio da memória, princípios de meta-cognição e codificação profunda.', 1, 7, 'focus-protocol-l2-phase-1', 'Memória Ativada')
  RETURNING id INTO v_phase1_id;

  INSERT INTO public.journey_phases (journey_id, phase_number, title, subtitle, description, day_start, day_end, badge_illustration_key, badge_name)
  VALUES (v_journey_id, 2, 'SISTEMA', 'Seu segundo cérebro', E'Zettelkasten, processamento de notas, conexões entre ideias, fluxo de conhecimento e revisão espaçada avançada.', 8, 14, 'focus-protocol-l2-phase-2', 'Zettelkasten Montado')
  RETURNING id INTO v_phase2_id;

  INSERT INTO public.journey_phases (journey_id, phase_number, title, subtitle, description, day_start, day_end, badge_illustration_key, badge_name)
  VALUES (v_journey_id, 3, 'PRODUÇÃO', 'De consumidor a produtor', E'Produção de output, leitura seletiva, interleaving avançado, deep work de 2-3h e projetos de aprendizado.', 15, 22, 'focus-protocol-l2-phase-3', 'Produtor de Conhecimento')
  RETURNING id INTO v_phase3_id;

  INSERT INTO public.journey_phases (journey_id, phase_number, title, subtitle, description, day_start, day_end, badge_illustration_key, badge_name)
  VALUES (v_journey_id, 4, 'MESTRIA', 'A máquina de aprender', E'Integração total, protocolo permanente de aprendizado acelerado, projetos avançados e graduação.', 23, 30, 'focus-protocol-l2-phase-4', 'Aprendizado Acelerado')
  RETURNING id INTO v_phase4_id;

  -- ============================================
  -- 2. Journey Days (30 days)
  -- ============================================

  -- DAY 1
  INSERT INTO public.journey_days (journey_id, phase_id, day_number, title, card_content, estimated_minutes) VALUES
  (v_journey_id, v_phase1_id, 1, 'O upgrade: de foco para aprendizado', E'Você dominou sua atenção no Nível 1. Agora vamos dominar seu APRENDIZADO. A diferença? Foco é sentar e trabalhar. Aprendizado é transformar o que entra no cérebro em conhecimento permanente.\n\n**Diagnóstico de aprendizado:**\n- Quando termina um curso/livro, quanto lembra 30 dias depois? ___%\n- Tem algum sistema para guardar o que aprende? Sim / Não\n- Consegue explicar o último conceito que estudou? Sim / Não\n- Quanto do tempo de estudo é CONSUMINDO vs PRODUZINDO? ___% / ___%\n\n**O framework de meta-aprendizado:**\nTodo aprendizado eficaz segue um ciclo:\nABSORVER → PROCESSAR → RETER → APLICAR → PRODUZIR\n\nA maioria para no primeiro passo e pula o resto. Resultado: ilusão de aprendizado.\n\n**NOVO HÁBITO — Palácio da memória:**\nA partir de hoje, pratique memorização espacial por pelo menos 10 min/dia. Meta-análise de 2025 confirmou efeito GRANDE na recordação (d = 0.88).\n\n**Hoje:** Suas sessões de deep work DEVEM incluir pelo menos 1 etapa além de absorver. Estudou algo? Feche o material e escreva o que entendeu.', 90);

  -- DAY 2
  INSERT INTO public.journey_days (journey_id, phase_id, day_number, title, card_content, estimated_minutes) VALUES
  (v_journey_id, v_phase1_id, 2, 'Leitura ativa: o fim do grifar passivo', E'Grifar texto é o equivalente intelectual de assistir alguém malhar e achar que ficou mais forte. Parece estudo, mas não é.\n\n**Por que grifar e reler NÃO funcionam:**\n- Criam ilusão de fluência: material parece familiar, então você acha que aprendeu\n- Não exigem processamento profundo — cérebro fica no modo passivo\n\n**Protocolo de leitura ativa:**\n\n**ANTES (2-3 min):** Escaneie título, subtítulos, gráficos. Pergunte: "O que espero aprender?"\n\n**DURANTE:** Transforme cada seção em perguntas. A cada parágrafo importante, reformule nas suas palavras. Anote reações e dúvidas.\n\n**DEPOIS (5-10 min):** Feche o material. Blurting: escreva os 3-5 pontos principais de memória. Compare com o material.\n\n**Exercício:** Escolha um artigo ou capítulo. Aplique o protocolo completo. A leitura ativa pode ser mais lenta, mas a RETENÇÃO é incomparavelmente superior.', 100);

  -- DAY 3
  INSERT INTO public.journey_days (journey_id, phase_id, day_number, title, card_content, estimated_minutes) VALUES
  (v_journey_id, v_phase1_id, 3, 'Técnica Feynman: ensine para aprender', E'Richard Feynman, Nobel de Física, tinha uma regra: se não consegue explicar para uma criança de 12 anos, você não entendeu de verdade.\n\n**NOVO HÁBITO — Técnica Feynman diária:**\nUma vez por dia, escolha 1 conceito que estudou e explique nas suas palavras como se fosse para alguém que não sabe NADA do assunto.\n\n**O protocolo Feynman completo:**\n1. Escolha e estude UM conceito\n2. Explique com simplicidade — sem jargão, com analogias e exemplos\n3. Identifique os gaps — onde travou? O que não conseguiu explicar?\n4. Volte à fonte, preencha os gaps, simplifique ainda mais\n\n**O critério de parada:** "Clareza Feynmaniana" — quando consegue explicar fluentemente, sem travar. Aí APRENDEU.\n\n**Exemplo prático:**\n- Ruim: "BDNF modula plasticidade sináptica via cascatas MAPK e CaMKII"\n- Feynman: "Exercício faz seu cérebro produzir um fertilizante para neurônios chamado BDNF, que melhora memória e aprendizado"\n\n**Dica:** Gravar áudio da explicação é ainda mais eficaz — falar exige processamento mais profundo que escrever.', 100);

  -- DAY 4
  INSERT INTO public.journey_days (journey_id, phase_id, day_number, title, card_content, estimated_minutes) VALUES
  (v_journey_id, v_phase1_id, 4, 'Encoding: como gravar no cérebro', E'A memória não é como um HD. Memorizar exige CODIFICAÇÃO ativa. Quanto mais vívida, emocional e conectada, mais forte a memória.\n\n**Os 4 princípios da codificação poderosa:**\n\n**1. Elaboração:** Conecte com o que já sabe. "Esse conceito lembra o quê? Se parece com o quê?" Uma ideia isolada é frágil. Conectada a 5 outras é robusta.\n\n**2. Visualização:** O cérebro processa imagens ~60.000x mais rápido que texto. Transforme conceitos abstratos em imagens concretas e absurdas.\n\n**3. Associação:** Crie pontes — acrônimos, rimas, analogias, histórias.\n\n**4. Emoção:** Memórias emocionais são muito mais fortes. Pergunte: "Por que isso IMPORTA para mim?"\n\n**Exercício:** Pegue 5 conceitos que estudou recentemente. Para cada um, crie: 1 conexão com algo que já sabia, 1 imagem mental vívida, 1 analogia e 1 razão pessoal.', 90);

  -- DAY 5
  INSERT INTO public.journey_days (journey_id, phase_id, day_number, title, card_content, estimated_minutes) VALUES
  (v_journey_id, v_phase1_id, 5, 'Revisão espaçada avançada', E'No Nível 1 você aprendeu repetição espaçada. Agora vamos implementar um SISTEMA completo de revisão que garante retenção de 90%+ a longo prazo.\n\n**NOVO HÁBITO — Leitura com anotações:**\nA partir de hoje, toda leitura de estudo inclui anotações ativas nas suas palavras. Mínimo 20 min/dia.\n\n**O sistema de revisão em 3 camadas:**\n\n**Camada 1 — Flashcards com Anki (diário, 10-20 min):**\nCrie flashcards para cada conceito importante. Uma informação por card, pergunta específica, use imagens quando possível.\n\n**Camada 2 — Blurting semanal (1x/semana, 15-20 min):**\nFolha em branco, cronômetro de 10 min. Escreva TUDO que lembra. Compare com material. Crie flashcards para os gaps.\n\n**Camada 3 — Ensino mensal (1x/mês):**\nPrepare uma "aula" de 10-15 min sobre o tema mais importante do mês. Dê a aula para alguém ou grave.\n\n**Cronograma ideal:**\n- Todo dia: Flashcards Anki (10-20 min)\n- 1x/semana: Blurting do tema principal (15-20 min)\n- 1x/mês: Ensinar conceito principal (30-60 min)', 100);

  -- DAY 6
  INSERT INTO public.journey_days (journey_id, phase_id, day_number, title, card_content, estimated_minutes) VALUES
  (v_journey_id, v_phase1_id, 6, 'Palácio da memória: seu primeiro', E'Meta-análise de 2025 (British Journal of Psychology) confirmou: o método de loci tem efeito GRANDE na recordação (d = 0.88). Atletas de memória entre os top 50 mundial usam essa técnica.\n\n**Construindo seu primeiro palácio:**\n\n**Passo 1 — Escolha o lugar (5 min):** Um lugar que conhece EXTREMAMENTE bem — seu apartamento, casa onde cresceu, trajeto do trabalho.\n\n**Passo 2 — Defina 10-15 pontos FIXOS na ordem:** porta → sapateira → sofá → mesa → TV → cozinha → geladeira → fogão → quarto → cama → escrivaninha → janela → banheiro → chuveiro.\n\n**Passo 3 — Pratique a rota vazia 3x.** Cada ponto deve ser cristalino.\n\n**Passo 4 — Primeira memorização:** Crie imagens VÍVIDAS e ABSURDAS associando cada item a um ponto. Quanto mais absurda, emocional e exagerada, mais memorável.\n\n**Regras de ouro:** Use AÇÃO e MOVIMENTO. Envolva SENTIDOS (som, cheiro, textura). Use EMOÇÃO (humor, nojo, surpresa). EXAGERE a escala.\n\n**Teste:** Feche os olhos, "caminhe" pelo palácio. Quantos itens lembrou? Se 8+/10, está funcionando.', 95);

  -- DAY 7
  INSERT INTO public.journey_days (journey_id, phase_id, day_number, title, card_content, is_review_day, estimated_minutes) VALUES
  (v_journey_id, v_phase1_id, 7, 'Review semanal #1', E'Primeira semana do Nível 2. Você tem 3 novas ferramentas: leitura ativa, Feynman e palácio da memória.\n\n**Palácio funcional — Use para algo REAL:**\nHoje, use seu palácio para memorizar algo que PRECISA saber: 10 termos de uma matéria, 10 palavras em outro idioma, 10 conceitos-chave de um livro.\n\n**Review semanal #1:**\n1. Deep work total da semana: ___ min\n2. Sessão mais longa: ___ min\n3. Técnica Feynman praticada: ___/7 dias\n4. Leitura ativa praticada: ___/7 dias\n5. Palácio da memória — itens memorizados: ___\n6. Hora média de dormir: ___:___\n7. Nota de eficácia de aprendizado (1-10): ___\n\n**Compare com o início:**\n- Retenção percebida: Melhor / Igual / Pior\n- Processamento após estudo: Faço / Às vezes / Não faço\n\n**Badge: "Memória Ativada"**', true, 30);

  -- DAY 8
  INSERT INTO public.journey_days (journey_id, phase_id, day_number, title, card_content, estimated_minutes) VALUES
  (v_journey_id, v_phase2_id, 8, 'Zettelkasten: por que notas tradicionais falham', E'Niklas Luhmann publicou 70 livros e 500+ artigos em 30 anos. Seu segredo: uma caixa com 90.000 fichas interconectadas — o Zettelkasten.\n\n**NOVO HÁBITO — Zettelkasten:**\nA cada sessão de estudo, crie pelo menos 1-3 notas permanentes conectadas no seu segundo cérebro.\n\n**Por que notas lineares falham:**\n- Presas na ordem cronológica, nunca revisitadas\n- Impossível conectar ideia da página 3 com ideia da página 87\n- Zero geração de insights — notas não "conversam"\n\n**O Zettelkasten resolve:**\n- Cada nota é atômica (uma ideia)\n- Notas se conectam por links (como páginas da web)\n- Conexões criam insights que você NÃO teria sozinho\n- O sistema fica MAIS útil conforme cresce\n\n**Os 3 tipos de notas:**\n1. Fleeting (transitórias): ideias rápidas — temporárias\n2. Literature (leitura): resumos sobre material lido\n3. Permanent (permanentes): ideias processadas, nas suas palavras, conectadas\n\n**Regras:** Uma ideia por nota. Sempre nas suas palavras. Conecte cada nota a pelo menos uma outra. Explique POR QUE estão ligadas.', 100);

  -- DAY 9
  INSERT INTO public.journey_days (journey_id, phase_id, day_number, title, card_content, estimated_minutes) VALUES
  (v_journey_id, v_phase2_id, 9, 'Setup: montando seu Zettelkasten', E'Hoje é dia de setup. Vamos montar a estrutura do seu segundo cérebro.\n\n**Escolha sua ferramenta (recomendação: Obsidian):**\n- Gratuito, funciona offline, markdown, links bidirecionais nativos\n- Visualização em grafo — vê as conexões entre notas\n\n**Setup mínimo (15-20 min):**\n1. Baixe e instale Obsidian\n2. Crie um vault chamado "Zettelkasten"\n3. Crie 4 pastas: /0-Inbox, /1-Permanentes, /2-Literatura, /3-Projetos\n4. Crie um template de nota permanente com: Título, Tags, Fonte, Ideia nas suas palavras, Por que importa, Conexões com links, Perguntas abertas\n\n**Não precisa mais que isso para começar.** O sistema cresce organicamente. Perfeccionismo no setup é a armadilha #1.\n\n**Hoje, crie suas primeiras 3 notas permanentes** sobre conceitos desta jornada. Conecte-as entre si.', 100);

  -- DAY 10
  INSERT INTO public.journey_days (journey_id, phase_id, day_number, title, card_content, is_cliff_day, estimated_minutes) VALUES
  (v_journey_id, v_phase2_id, 10, 'Suas primeiras notas permanentes', E'O Zettelkasten está montado. Hoje, o fluxo de processamento vira hábito.\n\n**O fluxo:** Fonte → Nota de literatura → Nota(s) permanente(s) → Conexões\n\n**Exercício — Crie 5 notas permanentes:**\nPegue algo que estudou recentemente e crie 5 notas atômicas:\n1. Uma ideia por nota, nas suas palavras\n2. Conecte cada nota a pelo menos uma outra\n3. Escreva POR QUE conectou\n\n**Exemplo de conexões:**\n- "Resíduo de atenção reduz capacidade cognitiva" → conecta com "Flow state exige 15-20 min sem interrupção"\n- "Deep work tem limite de ~4h/dia" → conecta com "Mielinização precisa de foco repetido, não volume"\n\n**Se está achando trabalhoso:** É normal. O pipeline leitura → captura → processamento → conexão parece lento no início. Depois de 2 semanas, vira automático. O cliff do sistema de notas é aqui — a maioria desiste antes de ver o efeito composto.', true, 100);

  -- DAY 11
  INSERT INTO public.journey_days (journey_id, phase_id, day_number, title, card_content, is_cliff_day, estimated_minutes) VALUES
  (v_journey_id, v_phase2_id, 11, 'O fluxo: da leitura à nota permanente', E'O poder do Zettelkasten vem do FLUXO contínuo: tudo que entra no cérebro passa por processamento e vira conhecimento conectado.\n\n**O pipeline completo de aprendizado:**\n\n**1. CAPTURA (durante leitura):** Notas rápidas no Inbox. Formato: "Fonte: ___ | Ideia: ___ | Minha reação: ___". NÃO processe agora.\n\n**2. PROCESSAMENTO (sessão dedicada, 1x/dia):** Para cada captura, pergunte: "Vale guardar?" Se sim: reescreva nas suas palavras (Feynman simplificado). Se não: delete.\n\n**3. CONEXÃO (parte mais importante):** Antes de fechar a nota: "Com que outras notas isso se conecta?" Crie links bidirecionais. Escreva POR QUE conectou.\n\n**4. REVISÃO (semanal):** Revise notas da semana, procure conexões que não viu antes, identifique clusters.\n\n**Exercício:** Sessão de leitura ativa de 30-45 min usando o pipeline completo. Meta: pelo menos 3 notas permanentes conectadas.\n\n**Se está travando no processamento:** Reduza a ambição. 1 nota permanente BEM FEITA > 5 notas apressadas.', true, 110);

  -- DAY 12
  INSERT INTO public.journey_days (journey_id, phase_id, day_number, title, card_content, is_cliff_day, estimated_minutes) VALUES
  (v_journey_id, v_phase2_id, 12, 'Palácio da memória expandido', E'Seu primeiro palácio tem 10-15 pontos. Agora vamos expandir: mais palácios, mais capacidade.\n\n**Expandindo seu arsenal:**\n\n**Palácio #2 — Outro lugar familiar:** Casa de amigo, escola, shopping, academia. Defina 10-15 pontos. Agora você tem 20-30 slots de memória.\n\n**Palácio #3 — Trajeto:** Um trajeto regular (casa → trabalho). Pontos = marcos do caminho (padaria, ponto de ônibus, semáforo...).\n\n**Aplicação real — Estudando com palácio:**\n- Listas ordenadas (etapas de processos, cronologias)\n- Vocabulário de idiomas\n- Conceitos-chave de provas\n- Roteiro de apresentações\n\n**Combinação palácio + repetição espaçada:**\nDia 1: Memorize no palácio → Dia 2: Caminhe sem consultar → Dia 4: Caminhe → Dia 7: Caminhe → Dia 14: Se tudo ficou, está na memória de longo prazo.\n\n**Exercício:** Construa Palácio #2. Memorize 10 conceitos de algo que precisa aprender.', true, 100);

  -- DAY 13
  INSERT INTO public.journey_days (journey_id, phase_id, day_number, title, card_content, is_rest_day, motivational_note, estimated_minutes) VALUES
  (v_journey_id, v_phase2_id, 13, 'Conexões que geram insights', E'Luhmann dizia que o Zettelkasten era seu "parceiro de conversa" — encontrava conexões que não tinha percebido. Hoje é dia de descanso ativo: foco em conexões, não absorção.\n\n**Notas de estrutura (MOCs — Maps of Content):**\nQuando um cluster de notas cresce, crie uma nota-mãe que organiza o cluster. Exemplo:\n\n"MOC: Técnicas de Aprendizado"\n- Memória: curva de Ebbinghaus, palácio, repetição espaçada\n- Processamento: Feynman, active recall, codificação elaborativa\n- Sistemas: Zettelkasten, pipeline, regra 70/30\n- Conexões com saúde: exercício + BDNF, sono + consolidação\n\n**Perguntas-ponte:**\n- "Isso contradiz algo que já sei?" → tensão gera insight\n- "Se combinar essa ideia com outra, o que resulta?" → síntese criativa\n\n**Revisão aleatória:** Abra 3-5 notas aleatórias. Pergunte: "Alguma conexão que não percebi?"\n\n**Hoje:** Sem absorção nova. Apenas conecte, revise e descanse. O cérebro consolida durante o descanso.', true, 'Descanso ativo: o cérebro consolida conexões enquanto você desacelera. Confie no processo.', 45);

  -- DAY 14
  INSERT INTO public.journey_days (journey_id, phase_id, day_number, title, card_content, is_review_day, estimated_minutes) VALUES
  (v_journey_id, v_phase2_id, 14, 'Review semanal #2', E'Duas semanas. Você tem leitura ativa, Feynman, palácio da memória e Zettelkasten. Hora de avaliar o sistema.\n\n**Review semanal #2:**\n1. Deep work total: ___ min\n2. Notas Zettelkasten criadas esta semana: ___\n3. Total de notas no Zettelkasten: ___\n4. Flashcards criados no Anki: ___\n5. Revisão diária de Anki: ___/7 dias\n6. Feynman praticado: ___/7 dias\n7. Palácios em uso: ___ (com ___ pontos cada)\n8. Nota de eficácia de aprendizado (1-10): ___\n\n**Checkpoint — Seu pipeline está rodando?**\n- [ ] Leio → capturo no Inbox\n- [ ] Processo no mesmo dia → notas permanentes\n- [ ] Conecto com notas existentes\n- [ ] Reviso flashcards diariamente\n- [ ] Pratico Feynman pelo menos 3x/semana\n\n**Badge: "Zettelkasten Montado"**', true, 30);

  -- DAY 15
  INSERT INTO public.journey_days (journey_id, phase_id, day_number, title, card_content, estimated_minutes) VALUES
  (v_journey_id, v_phase3_id, 15, 'Output: a regra 70/30', E'Consumir conhecimento sem produzir nada é entretenimento intelectual, não aprendizado. A partir de hoje, toda semana você PRODUZ algo.\n\n**NOVO HÁBITO — Produzir output:**\nPelo menos 1x por semana, produza algo tangível a partir do que estudou.\n\n**A regra 70/30:**\n- 30% do tempo: absorvendo (lendo, assistindo, estudando)\n- 70% do tempo: produzindo (escrevendo, praticando, ensinando)\n\n**Formas de output (do simples ao complexo):**\n1. Nota Zettelkasten conectada (5-15 min)\n2. Thread/post com 5-10 insights (15-30 min)\n3. Resumo ensinável — Feynman de 1 página (30-60 min)\n4. Artigo/blog post de 800-1500 palavras (1-3h)\n5. Tutorial/vídeo ensinando o que aprendeu (2-5h)\n6. Projeto aplicado real (5-20h)\n\n**Learning by teaching:** Preparar-se para ensinar melhora retenção mais do que estudar para prova. Mesmo que nunca publique, o ato de preparar a explicação já consolida.\n\n**Exercício:** Escolha algo que aprendeu nesta jornada. Produza um output: thread de 5-10 tweets ou texto de 1 página.', 100);

  -- DAY 16
  INSERT INTO public.journey_days (journey_id, phase_id, day_number, title, card_content, estimated_minutes) VALUES
  (v_journey_id, v_phase3_id, 16, 'Leitura seletiva: não leia tudo', E'Ler mais não significa aprender mais. Ler os livros CERTOS, nas partes CERTAS, é mais valioso que ler 50 livros inteiros sem processar.\n\n**Triagem antes de ler (5 min):**\n1. Resenhas/resumos → vale seu tempo?\n2. Índice → quais capítulos são relevantes para SEU objetivo?\n3. Introdução e conclusão → captura a tese principal?\n4. Decisão: ler inteiro, ler parcial, ou pular?\n\n**Regra: 3 livros ao mesmo tempo, 3 velocidades:**\n1. Livro de estudo profundo (leitura ativa + Zettelkasten + Feynman)\n2. Livro de escaneamento (skimming, extração rápida)\n3. Livro de lazer (ficção, biografias leves)\n\n**A regra das 50 páginas:** Se após 50 páginas não está agregando, largue sem culpa. Existem livros demais no mundo.\n\n**A matriz de leitura:**\n- Alto valor + denso → Leitura profunda + notas + Feynman\n- Alto valor + leve → Leitura ativa, notas seletivas\n- Baixo valor + denso → Skimming ou pular\n- Baixo valor + leve → Entretenimento (não conte como estudo)', 100);

  -- DAY 17
  INSERT INTO public.journey_days (journey_id, phase_id, day_number, title, card_content, estimated_minutes) VALUES
  (v_journey_id, v_phase3_id, 17, 'Deep work 2.0: sessões de 2-3 horas', E'No Nível 1, 90 minutos era o teto. Agora vamos quebrar a barreira das 2 horas.\n\n**Protocolo para sessão estendida (2-3h):**\n[0-5 min] RITUAL: preparação, mini-meditação\n[5-90 min] BLOCO 1: foco profundo\n[90-110 min] PAUSA REAL: 20 min (caminhar, NÃO checar celular)\n[110-170 min] BLOCO 2: foco profundo\n[170-180 min] ENCERRAMENTO: registro, shutdown\n\n**A chave: a pausa do meio.**\nSAIA da cadeira. Caminhe, alongue, olhe pela janela. Deixe a mente divagar — o modo default processa o que acabou de estudar. 20 min é o mínimo.\n\n**Progressão semanal N2:**\n- Semana 1 (Dias 1-7): 90-120 min\n- Semana 2 (Dias 8-14): 120-150 min\n- Semana 3 (Dias 15-22): 150-180 min\n- Semana 4 (Dias 23-30): 180-240 min = 3-4h\n\n**Aviso:** 4h de deep work REAL por dia é o limite prático. Não se compare com quem diz estudar 10h — provavelmente 7 são shallow work disfarçado.', 120);

  -- DAY 18
  INSERT INTO public.journey_days (journey_id, phase_id, day_number, title, card_content, estimated_minutes) VALUES
  (v_journey_id, v_phase3_id, 18, 'Interleaving + elaboração avançada', E'Técnicas avançadas de codificação para turbinar a retenção.\n\n**Interleaving estratégico — Sessão de 90 min:**\n[0-25 min] Tema A — absorção\n[25-30 min] Active recall Tema A (blurting)\n[30-55 min] Tema B — absorção\n[55-60 min] Active recall Tema B\n[60-75 min] Revisão de A + B misturados\n[75-85 min] Teste misto (perguntas que exigem A e B)\n[85-90 min] Criar flashcards dos gaps\n\n**Elaboração interrogativa:** Em vez de aceitar informação, pergunte "POR QUÊ?" em camadas. Cada "por quê?" cria nova profundidade e novas conexões.\n\n**Dual coding:** Combine texto + visual SEMPRE. Faça diagramas, desenhe processos, visualize conceitos. Informação codificada em dois formatos (verbal + visual) tem retenção muito superior.\n\n**Exercício:** Aplique o interleaving em sua sessão de deep work de hoje. Alterne 2 temas com active recall entre eles.', 110);

  -- DAY 19
  INSERT INTO public.journey_days (journey_id, phase_id, day_number, title, card_content, estimated_minutes) VALUES
  (v_journey_id, v_phase3_id, 19, 'O projeto de aprendizado', E'Aprendizado sem projeto é turismo intelectual. Um projeto de aprendizado direciona o que você estuda, como estuda e quando para.\n\n**Definindo seu projeto:**\n- Objetivo claro: "Ser capaz de ___" (não "aprender sobre ___")\n- Prazo: 2-4 semanas\n- Output definido: algo tangível no final\n- Fontes curadas: 3-5 fontes principais (não 50)\n\n**Exemplos:**\n- Passar na certificação Google Analytics (3 sem) → Certificado obtido\n- Dominar SQL básico-intermediário (4 sem) → 50 queries + portfolio\n- Processar "Deep Work" de Cal Newport (2 sem) → 30+ notas Zettelkasten\n- Aprender fundamentos de Python (4 sem) → 3 scripts funcionando\n\n**Exercício — Defina SEU projeto:**\n- Objetivo: ___\n- Prazo: ___\n- Output final: ___\n- Fontes (máx 5): ___\n- Horas de deep work/semana: ___', 100);

  -- DAY 20
  INSERT INTO public.journey_days (journey_id, phase_id, day_number, title, card_content, estimated_minutes) VALUES
  (v_journey_id, v_phase3_id, 20, 'O Zettelkasten na prática: caso real', E'Exercício completo: pegar um capítulo/artigo, processar com o pipeline inteiro, ver o Zettelkasten em ação.\n\n**Pipeline completo (60-90 min):**\n\n**Fase 1 — Captura (20-30 min de leitura ativa):**\nEscolha um capítulo substancial. Leia com protocolo ativo. Capture ideias no Inbox.\n\n**Fase 2 — Processamento (15-20 min):**\nPara cada captura: reescreva nas suas palavras (Feynman). É permanente? Crie nota com template. É passageira? Delete.\n\n**Fase 3 — Conexão (10-15 min):**\nPara cada nota permanente: busque relacionadas, crie links bidirecionais, escreva POR QUE conectou, atualize MOCs.\n\n**Fase 4 — Teste (10 min):**\nFeche tudo. Explique os 3 conceitos principais (Feynman). Crie 5-10 flashcards no Anki.\n\n**Registre:** Notas: ___ | Conexões: ___ | Flashcards: ___\n\nEsse pipeline é o que separa quem estuda de quem APRENDE. Quanto mais repetir, mais automático fica.', 110);

  -- DAY 21
  INSERT INTO public.journey_days (journey_id, phase_id, day_number, title, card_content, is_review_day, estimated_minutes) VALUES
  (v_journey_id, v_phase3_id, 21, 'Review semanal #3', E'Três semanas. Seu sistema está rodando. Hora de otimizar.\n\n**Review semanal #3:**\n1. Deep work total: ___ min (meta: 150+ min/dia)\n2. Notas Zettelkasten criadas: ___ (total acumulado: ___)\n3. Conexões entre notas: ___ (estimativa)\n4. Anki: revisão diária ___/7 | cards acumulados: ___\n5. Output produzido esta semana: ___\n6. Projeto de aprendizado: ___% completo\n7. Palácios ativos: ___ com ___ pontos\n8. Nota de eficácia (1-10): ___\n\n**Perguntas de calibração:**\n- O pipeline leitura → captura → processamento → conexão está fluindo? Onde trava?\n- Estou usando as notas Zettelkasten ou só acumulando?\n- A proporção consumo/produção está mais perto de 30/70 ou 90/10?\n\n**Badge: "Produtor de Conhecimento"**', true, 30);

  -- DAY 22
  INSERT INTO public.journey_days (journey_id, phase_id, day_number, title, card_content, estimated_minutes) VALUES
  (v_journey_id, v_phase4_id, 22, 'Transferência: aplicar em contexto diferente', E'A prova de que aprendeu de VERDADE não é lembrar — é aplicar em contexto DIFERENTE.\n\n**Transferência de aprendizado — Os 3 níveis:**\n\n**Nível 1 — Recall:** "O que é BDNF?" → responder corretamente. Flashcard resolve.\n\n**Nível 2 — Aplicação:** "Desenhe um programa de exercícios para otimizar BDNF." Exige entender as variáveis.\n\n**Nível 3 — Transferência:** "Como BDNF e neuroplasticidade se aplicam a aprender um idioma?" Exige abstração + síntese + criatividade.\n\n**Exercício:** Pegue 3 conceitos do seu Zettelkasten. Para cada um:\n- "Como aplico no contexto original?"\n- "Como aplico em contexto COMPLETAMENTE diferente?"\n- "Se combinar com [outro conceito], o que resulta?"\n\nCrie novas notas de síntese com as respostas. Essas são as MAIS valiosas do seu Zettelkasten — insights que ninguém mais teria.', 100);

  -- DAY 23
  INSERT INTO public.journey_days (journey_id, phase_id, day_number, title, card_content, estimated_minutes) VALUES
  (v_journey_id, v_phase4_id, 23, '12 problemas favoritos', E'Feynman mantinha ~12 problemas que o intrigavam. Quando encontrava ideia nova, testava: "Isso me ajuda a resolver algum dos meus 12 problemas?"\n\n**Crie sua lista de 12 Problemas Favoritos:**\nProblemas que te intrigam, relevantes para sua vida e carreira.\n\n**Exemplos para um homem de 20-25 anos:**\n1. Como construir renda passiva enquanto jovem?\n2. Qual habilidade técnica vai me diferenciar mais?\n3. Como manter disciplina sem depender de motivação?\n4. Como reter o que estudo para usar na carreira?\n5. Como construir rede profissional forte?\n6. Qual o sistema ideal de organização para minha vida?\n7. Como equilibrar crescimento profissional e saúde mental?\n8. Como criar conteúdo que gere autoridade na minha área?\n9. Como aprender inglês fluente no próximo ano?\n10. Como tomar decisões melhores sob incerteza?\n11. Como construir hábitos que duram anos?\n12. Qual será minha próxima grande aposta profissional?\n\n**Como usar:** Quando aprender algo novo, teste contra a lista. Se conecta: aprofunde e linke no Zettelkasten. Revise mensalmente.\n\n**Exercício:** Escreva sua lista. Crie uma nota MOC no Zettelkasten para ela.', 100);

  -- DAY 24
  INSERT INTO public.journey_days (journey_id, phase_id, day_number, title, card_content, estimated_minutes) VALUES
  (v_journey_id, v_phase4_id, 24, 'Protocolo de estudo completo', E'Vamos consolidar TUDO em um protocolo único aplicável a qualquer tema.\n\n**O Protocolo de Aprendizado Acelerado:**\n\n**ANTES (5-10 min):**\n- Definir: "O que quero ser capaz de fazer após estudar?"\n- Pré-leitura: escanear estrutura do material\n- Ativar conhecimento prévio: "O que já sei?"\n- Ritual de deep work: ambiente, celular fora, timer\n\n**DURANTE (60-120 min):**\n- Leitura ativa: perguntas, marginália, pausas\n- Captura no Inbox do Zettelkasten\n- Pausa no meio: 15-20 min (caminhar, divagar)\n- Active recall parcial: blurting do que absorveu\n\n**DEPOIS (30-45 min):**\n- Active recall final + Feynman (1-3 conceitos)\n- Processar Inbox → notas permanentes\n- Conectar com notas existentes\n- Criar 5-15 flashcards para Anki\n\n**REVISÕES FUTURAS:**\nDia 1: Anki | Dia 3: Palácio | Dia 7: Blurting | Dia 14: Zettelkasten | Dia 30: Ensinar', 120);

  -- DAY 25
  INSERT INTO public.journey_days (journey_id, phase_id, day_number, title, card_content, estimated_minutes) VALUES
  (v_journey_id, v_phase4_id, 25, 'Aprendendo habilidades (não só informação)', E'Tudo até aqui focou em aprender INFORMAÇÃO (conceitos, fatos, teorias). E para HABILIDADES (programar, escrever, falar em público, tocar instrumento)?\n\n**Framework para aprender habilidades:**\n\n**1. Decomponha a habilidade:**\n"Aprender programação" é enorme. Decomponha: variáveis → condicionais → loops → funções → strings. Cada sub-habilidade pode ser praticada isoladamente.\n\n**2. Pratique deliberadamente:**\nPrática deliberada NÃO é repetição mecânica. Foque na sub-habilidade mais fraca. Trabalhe na borda do que consegue. Receba feedback rápido. Repita com ajustes.\n\n**3. Reduza o ciclo de feedback:**\nQuanto mais rápido o feedback, mais rápido o aprendizado. Programação: execute e veja. Escrita: peça review. Idioma: fale com nativos.\n\n**4. Pratique em contexto real:**\nProjetos > exercícios isolados. Quer SQL? Analise dataset real. Quer escrita? Publique artigo. Quer marketing? Crie campanha de verdade.\n\n**Regra 80/20:** 20% das sub-habilidades produzem 80% dos resultados. Identifique e foque nelas primeiro.', 100);

  -- DAY 26
  INSERT INTO public.journey_days (journey_id, phase_id, day_number, title, card_content, estimated_minutes) VALUES
  (v_journey_id, v_phase4_id, 26, 'O compounding do conhecimento', E'Conhecimento funciona como juros compostos: cada nova ideia se multiplica pelas que você já tem. Quem sabe 100 conceitos conectados aprende o 101o em minutos.\n\n**O efeito composto:**\nEstudante A: 20 livros/ano, não processa, não conecta. Após 5 anos: pouco acessível.\nEstudante B: 10 livros/ano, processa tudo no Zettelkasten, conecta, produz output. Após 5 anos: 5.000+ notas interconectadas, dezenas de artigos.\n\n**Projeção a longo prazo (3 notas/dia):**\n- 1 mês: ~90 notas | ~200 flashcards\n- 6 meses: ~540 notas | ~1.200 flashcards\n- 1 ano: ~1.000 notas | ~2.500 flashcards\n- 3 anos: ~3.000 notas = expertise em múltiplas áreas\n\n**O fosso intelectual:** Quanto mais seu Zettelkasten cresce, mais RÁPIDO você aprende novos temas. Cada conceito novo encontra 10 conexões existentes. Um ativo acumulado que ninguém pode tirar.', 100);

  -- DAY 27
  INSERT INTO public.journey_days (journey_id, phase_id, day_number, title, card_content, estimated_minutes) VALUES
  (v_journey_id, v_phase4_id, 27, 'Armadilhas do nível 2', E'Com mais ferramentas vem mais formas de se sabotar.\n\n**As 8 armadilhas avançadas:**\n\n1. **Falácia do colecionador:** Salvar artigos em listas infinitas = sentir que aprendeu sem aprender. Se não processou, não aprendeu.\n\n2. **Perfeccionismo do Zettelkasten:** Mais tempo formatando que escrevendo. Nota imperfeita > nota perfeita que nunca existiu.\n\n3. **Tool hopping:** Obsidian → Notion → Logseq → de volta. Pare. Use uma por 6 meses antes de reavaliar.\n\n4. **Consumo infinito disfarçado:** 5 vídeos sobre "como estudar" em vez de ESTUDAR. Meta-aprendizado tem limite. Aplique, depois otimize.\n\n5. **Notas sem conexão:** Notas que não se conectam a nada = cemitério de ideias. Cada nota PRECISA de pelo menos 1 link.\n\n6. **Ignorar o output:** 500 notas, zero produção. O teste: "Consegui USAR esse conhecimento?"\n\n7. **Comparação com memory athletes:** Use o palácio para coisas ÚTEIS, não para memorizar pi.\n\n8. **Abandonar a base (N1):** Deep work, sono, celular fora — tudo do N1 CONTINUA sendo fundação. Técnicas avançadas sobre base fraca = castelo na areia.', 100);

  -- DAY 28
  INSERT INTO public.journey_days (journey_id, phase_id, day_number, title, card_content, is_review_day, estimated_minutes) VALUES
  (v_journey_id, v_phase4_id, 28, 'Review semanal #4 + Review mensal', E'**Review semanal #4:**\n1. Deep work total: ___ min\n2. Notas Zettelkasten criadas: ___\n3. Total acumulado de notas: ___\n4. Anki: cards acumulados: ___ | streak: ___ dias\n5. Outputs produzidos no mês: ___\n6. Projeto de aprendizado: ___% completo\n7. Palácios: ___ ativos com ___ pontos totais\n\n**Review mensal completo:**\n1. Deep work total do mês: ___ min (~___h)\n2. Progressão: Dia 1 (___ min/dia) → Dia 28 (___ min/dia)\n3. Total de notas Zettelkasten: ___\n4. Total de flashcards Anki: ___\n5. Outputs produzidos: ___\n6. Conceitos que consigo ensinar com Feynman: ___\n7. Projeto de aprendizado: status ___\n8. Maior insight do mês: ___\n9. Nota de eficácia de aprendizado (1-10): ___', true, 30);

  -- DAY 29
  INSERT INTO public.journey_days (journey_id, phase_id, day_number, title, card_content, estimated_minutes) VALUES
  (v_journey_id, v_phase4_id, 29, 'Seu protocolo permanente', E'O sistema que vai se compor exponencialmente ao longo dos próximos anos.\n\n**DIÁRIO (não-negociável):**\n- [ ] 2-3h de deep work (Tarefa #1 + blocos estruturados)\n- [ ] Time blocking do dia\n- [ ] Revisão de flashcards Anki (10-20 min)\n- [ ] Processar Inbox do Zettelkasten\n- [ ] Celular fora durante sessões\n- [ ] 7-9h de sono\n\n**SEMANAL:**\n- [ ] Review de métricas\n- [ ] Blurting semanal (tema principal)\n- [ ] 1 output produzido (post, artigo, vídeo, tutorial)\n- [ ] Revisão e conexão de notas Zettelkasten\n- [ ] Caminhar pelos palácios (revisão)\n- [ ] Leitura focada (mínimo 2-3h/semana)\n\n**MENSAL:**\n- [ ] Ensinar 1 conceito complexo (Feynman completo)\n- [ ] Audit de progresso\n- [ ] Revisar lista de 12 Problemas Favoritos\n- [ ] Avaliar/iniciar novo projeto de aprendizado\n- [ ] Revisar MOCs do Zettelkasten\n\n**TRIMESTRAL:**\n- [ ] Podar Zettelkasten (remover notas mortas)\n- [ ] Avaliar progresso nos 12 Problemas\n- [ ] Definir próximo projeto ambicioso', 100);

  -- DAY 30
  INSERT INTO public.journey_days (journey_id, phase_id, day_number, title, card_content, estimated_minutes) VALUES
  (v_journey_id, v_phase4_id, 30, 'GRADUAÇÃO: Aprendizado Acelerado', E'60 dias desde que começou o Protocolo de Foco Total. De 25 minutos sofridos para 3-4h de deep work com sistema completo de aprendizado.\n\n**Transformação — Nível 1 + Nível 2:**\n\n| Métrica | Início N1 | Fim N1 | Fim N2 |\n|---------|-----------|--------|--------|\n| Deep work diário | 0 min | 90-120 min | 180-240 min |\n| Foco ininterrupto | ~10 min | 60-90 min | 120+ min |\n| Sistema de estudo | Nenhum | Pomodoro + recall | Pipeline completo |\n| Retenção a 30 dias | ~10% | ~30-50% | ~80-90% |\n| Notas organizadas | Zero | Básicas | Zettelkasten ativo |\n| Output/produção | Zero | Ocasional | Semanal |\n| Palácios de memória | Zero | --- | 2-3 ativos |\n\n**O que você construiu:**\n- Pipeline completo: absorver → processar → reter → aplicar → produzir\n- Zettelkasten com notas interconectadas crescendo diariamente\n- Domínio da técnica Feynman para aprendizado profundo\n- Palácios da memória para memorização de alto desempenho\n- Repetição espaçada (Anki) para retenção de longo prazo\n- Hábito de produção de output (regra 70/30)\n- Lista de 12 Problemas Favoritos como bússola intelectual\n\n**Badge Final: "Aprendizado Acelerado"**\n**Badge de Jornada Completa: "Protocolo de Foco Total — Maestria"**', 15);

  -- ============================================
  -- 3. Habit Templates (NEW L2 habits only)
  -- ============================================
  -- Base habits from L1 (deep_work_session, focus_mode, daily_task_1,
  -- bedtime_tracking, phone_free_block, focused_reading, time_blocking,
  -- active_recall, spaced_repetition, weekly_focus_review) carry over
  -- and are NOT re-seeded here.

  -- 1. Palácio da memória (Day 1, timer, minutes, 10→15→20 min)
  INSERT INTO public.journey_habit_templates (journey_id, name, emoji, category, period, tracking_type, unit, initial_goal_value, start_day, end_day, frequency_type, goal_progression, canonical_key, sort_order) VALUES
  (v_journey_id, 'Palácio da memória', '🏛️', 'mente', 'morning', 'timer', 'minutes', 10, 1, NULL, 'daily',
   '[{"from_day":8,"goal_value":15},{"from_day":15,"goal_value":20}]'::jsonb,
   'memory_palace', 1);

  -- 2. Técnica Feynman (Day 3, checkbox)
  INSERT INTO public.journey_habit_templates (journey_id, name, emoji, category, period, tracking_type, start_day, end_day, frequency_type, canonical_key, sort_order) VALUES
  (v_journey_id, 'Técnica Feynman', '🧠', 'mente', 'afternoon', 'checkbox', 3, NULL, 'daily', 'feynman_technique', 2);

  -- 3. Leitura com anotações (Day 5, timer, minutes, 20→30 min)
  INSERT INTO public.journey_habit_templates (journey_id, name, emoji, category, period, tracking_type, unit, initial_goal_value, start_day, end_day, frequency_type, goal_progression, canonical_key, sort_order) VALUES
  (v_journey_id, 'Leitura com anotações', '📖', 'mente', 'morning', 'timer', 'minutes', 20, 5, NULL, 'daily',
   '[{"from_day":15,"goal_value":30}]'::jsonb,
   'annotated_reading', 3);

  -- 4. Zettelkasten (Day 8, checkbox)
  INSERT INTO public.journey_habit_templates (journey_id, name, emoji, category, period, tracking_type, start_day, end_day, frequency_type, canonical_key, sort_order) VALUES
  (v_journey_id, 'Zettelkasten', '📝', 'mente', 'afternoon', 'checkbox', 8, NULL, 'daily', 'zettelkasten', 4);

  -- 5. Ensinar/produzir conteúdo (Day 15, checkbox)
  INSERT INTO public.journey_habit_templates (journey_id, name, emoji, category, period, tracking_type, start_day, end_day, frequency_type, canonical_key, sort_order) VALUES
  (v_journey_id, 'Ensinar/produzir conteúdo', '🎯', 'mente', 'afternoon', 'checkbox', 15, NULL, 'daily', 'teach_produce', 5);

  -- 6. Review semanal (Day 7, weekly on Sunday, checkbox)
  INSERT INTO public.journey_habit_templates (journey_id, name, emoji, category, period, tracking_type, start_day, end_day, frequency_type, days_of_week, canonical_key, sort_order) VALUES
  (v_journey_id, 'Review semanal de aprendizado', '📊', 'mente', 'evening', 'checkbox', 7, NULL, 'weekly', '{0}', 'weekly_review_focus', 6);

END $$;
