-- ============================================
-- SEED: Finances L1 — "Controle Total"
-- ============================================
-- NOTE: The journeys row for 'finances-l1' already exists
-- from 20260218000001_seed_digital_detox_l1.sql.
-- This migration seeds phases, days, and habit templates only.

DO $$
DECLARE
  v_journey_id uuid;
  v_phase1_id uuid;
  v_phase2_id uuid;
  v_phase3_id uuid;
  v_phase4_id uuid;
BEGIN
  SELECT id INTO v_journey_id FROM public.journeys WHERE slug = 'finances-l1';

  -- ============================================
  -- 1. Phases
  -- ============================================

  INSERT INTO public.journey_phases (journey_id, phase_number, title, subtitle, description, day_start, day_end, badge_illustration_key, badge_name)
  VALUES (v_journey_id, 1, 'DIAGNÓSTICO', 'Veja a verdade', E'Nenhuma restrição de gastos. O objetivo é sair da cegueira financeira e medir para onde vai seu dinheiro.', 1, 7, 'finances-phase-1', 'Olhos Abertos')
  RETURNING id INTO v_phase1_id;

  INSERT INTO public.journey_phases (journey_id, phase_number, title, subtitle, description, day_start, day_end, badge_illustration_key, badge_name)
  VALUES (v_journey_id, 2, 'SISTEMA', 'Monte a máquina', E'Montar orçamento, definir categorias, identificar vazamentos e configurar as primeiras automações.', 8, 14, 'finances-phase-2', 'Sistema Montado')
  RETURNING id INTO v_phase2_id;

  INSERT INTO public.journey_phases (journey_id, phase_number, title, subtitle, description, day_start, day_end, badge_illustration_key, badge_name)
  VALUES (v_journey_id, 3, 'AÇÃO', 'Corte o desperdício, construa a reserva', E'Reduzir gastos desnecessários, automatizar poupança, iniciar reserva de emergência e lidar com dívidas.', 15, 22, 'finances-phase-3', 'Reserva Iniciada')
  RETURNING id INTO v_phase3_id;

  INSERT INTO public.journey_phases (journey_id, phase_number, title, subtitle, description, day_start, day_end, badge_illustration_key, badge_name)
  VALUES (v_journey_id, 4, 'CONSOLIDAÇÃO', 'Seu sistema financeiro', E'Consolidar hábitos, ajustar orçamento com dados reais, criar protocolo permanente e preparar para Nível 2.', 23, 30, 'finances-phase-4', 'Controle Total')
  RETURNING id INTO v_phase4_id;

  -- ============================================
  -- 2. Journey Days (30 days)
  -- ============================================

  -- DAY 1
  INSERT INTO public.journey_days (journey_id, phase_id, day_number, title, card_content, estimated_minutes) VALUES
  (v_journey_id, v_phase1_id, 1, 'O raio-x financeiro', E'Antes de mudar qualquer coisa, vamos ver a realidade. Hoje você só precisa fazer 3 coisas: registrar, pausar e revisar.\n\n**Tarefa 1 — Seu baseline financeiro:**\nPegue seu extrato bancário (app do banco) e anote:\n- Renda mensal líquida (o que cai na conta): R$___\n- Gasto total no último mês: R$___\n- Saldo atual na conta: R$___\n- Valor em poupança/investimento: R$___\n- Dívidas ativas (cartão, empréstimo, parcelas): R$___\n- Sobra ou falta no final do mês passado: R$___\n\n**Este é seu ponto zero.** Não julgue. Não entre em pânico. Isso é diagnóstico, não sentença.\n\nSe você é como 47% dos jovens Gen Z no Brasil, você não faz nenhum controle financeiro. Se está endividado, faz parte dos 39% dos brasileiros nessa situação. Você não é burro — ninguém te ensinou.\n\n**Tarefa 2 — Registrar gastos:**\nA partir de agora, registre TODO gasto do dia. Café, almoço, Uber, parcela — tudo. Formato simples: data | valor | descrição | categoria.\n\n**Não mude nenhum hábito de gasto.** Gaste normalmente. Queremos ver a verdade, não uma versão editada.\n\n**Tarefa 3 — Pausa de 10 segundos:**\nAntes de cada compra não-essencial hoje, pause 10 segundos e pergunte: "Eu realmente preciso disso agora?" Você ainda pode comprar — só precisa pausar antes.\n\n**Tarefa 4 — Check noturno (2 min):**\nAntes de dormir, some os gastos do dia. Só isso. Olhe o número.\n\n**A ciência:** O simples ato de registrar gastos muda comportamento. Funciona pelo mesmo princípio do diário alimentar — quando você vê a verdade preto no branco, decisões melhores acontecem naturalmente.', 20);

  -- DAY 2
  INSERT INTO public.journey_days (journey_id, phase_id, day_number, title, card_content, estimated_minutes) VALUES
  (v_journey_id, v_phase1_id, 2, 'Pra onde vai seu dinheiro?', E'Ontem você começou a registrar. Hoje vamos categorizar. Não é sobre quanto você gasta — é sobre PRA ONDE vai.\n\n**Exercício — Mapeamento de gastos (último mês):**\nAbra o extrato do banco/cartão dos últimos 30 dias. Classifique cada gasto:\n\n| Categoria | Exemplos | Total mês |\n|-----------|----------|----------|\n| 🏠 Moradia | Aluguel, condomínio, luz, água, internet | R$___ |\n| 🍔 Alimentação | Mercado, iFood, restaurante, padaria | R$___ |\n| 🚗 Transporte | Uber, gasolina, ônibus, metrô | R$___ |\n| 🎮 Lazer | Streaming, jogos, bares, shows | R$___ |\n| 📱 Assinaturas | Netflix, Spotify, gym, apps | R$___ |\n| 🛒 Compras | Roupas, eletrônicos, presentes | R$___ |\n| 💊 Saúde | Farmácia, consultas, plano | R$___ |\n| 💳 Dívidas | Parcelas, empréstimos, juros | R$___ |\n\n**Agora calcule:**\n- % da renda com necessidades (moradia + alimentação essencial + transporte + saúde)\n- % da renda com desejos (lazer + assinaturas + compras + delivery)\n- % poupada/investida\n\n**Micro-aula — O Fator Latte:**\nUm café de R$8/dia = R$240/mês = R$2.880/ano. Se investido a 10%/ano por 10 anos, vira ~R$50.000. O iFood de R$30 3x/semana = R$360/mês = R$4.320/ano. Esses "pequenos" gastos são o maior vazamento financeiro de quem tem 20-25 anos.', 20);

  -- DAY 3
  INSERT INTO public.journey_days (journey_id, phase_id, day_number, title, card_content, estimated_minutes) VALUES
  (v_journey_id, v_phase1_id, 3, 'Necessidade vs. desejo', E'Hoje vamos fazer o exercício mais importante da jornada inteira: separar o que você PRECISA do que você QUER.\n\n**Exercício — Classificação de gastos:**\nPegue sua lista de gastos do mês passado. Para CADA gasto, marque:\n\n- 🔴 **NECESSIDADE** — Se eu não pagar, algo grave acontece\n- 🟡 **CONFORTO** — Torna minha vida melhor, mas sobrevivo sem\n- 🟢 **DESEJO** — Puro prazer/entretenimento\n\n**A zona cinza:**\nA maioria dos erros financeiros acontece na categoria 🟡. Coisas que PARECEM necessidade mas são conforto:\n- iFood todo dia → você PODE cozinhar\n- Uber pra tudo → ônibus/metrô funciona\n- Plano de celular de R$100 → um de R$40 faz o mesmo\n- Academia de R$200 → existe de R$80 que funciona igual\n\n**Não estou dizendo pra cortar tudo.** Estou dizendo pra SABER que são escolhas, não obrigações. Quando você vê um gasto como "escolha", você tem poder sobre ele.\n\n**Regra do "Eu sobrevivo sem?":**\nPara cada gasto que classificou como necessidade, pergunte: "Se eu perdesse minha renda amanhã, eu continuaria pagando isso?" Se a resposta é não, não é necessidade.', 15);

  -- DAY 4
  INSERT INTO public.journey_days (journey_id, phase_id, day_number, title, card_content, estimated_minutes) VALUES
  (v_journey_id, v_phase1_id, 4, 'Seu dinheiro tem dono?', E'A maioria das pessoas não tem um "sistema" financeiro. Tem uma conta onde entra dinheiro e de onde sai dinheiro. Tudo misturado. Hoje vamos mudar isso.\n\n**Conceito — O dinheiro sem dono é gasto:**\nQuando todo seu dinheiro está em uma conta só, cada real que chega é "dinheiro disponível". Seu cérebro não diferencia o dinheiro do aluguel do dinheiro do bar.\n\n**Exercício — Contas com propósito:**\nMonte (ou planeje montar) a seguinte estrutura:\n1. **Conta corrente principal** — Onde entra o salário. Daqui saem as contas fixas\n2. **Reserva de emergência** — Conta separada (poupança ou CDB liquidez diária). Dinheiro que NÃO SE TOCA\n3. **Conta de gastos variáveis** — O que sobra na conta após separar o fixo\n\nSe usa Nubank, Inter ou C6: use os "cofrinhos" ou "caixinhas" como separadores.\n\n**A ciência — Mental accounting a seu favor:**\nPesquisa mostra que dividir dinheiro em "contas mentais" separadas aumenta a taxa de poupança. Quando o dinheiro está em um "cofrinho" rotulado "emergência", existe um custo psicológico de tirá-lo.\n\n**Regra prática:** Se seu banco permite criar subcategorias, crie HOJE:\n- 🏠 Contas fixas\n- 🎯 Reserva de emergência\n- 💸 Gastos do dia-a-dia', 15);

  -- DAY 5
  INSERT INTO public.journey_days (journey_id, phase_id, day_number, title, card_content, estimated_minutes) VALUES
  (v_journey_id, v_phase1_id, 5, 'Pague-se primeiro', E'A frase mais importante de finanças pessoais: "Não poupe o que sobra depois de gastar. Gaste o que sobra depois de poupar."\n\n**NOVO HÁBITO — Pague-se primeiro:**\n\nA lógica de 99% das pessoas:\nSalário → Pagar contas → Gastar → Ver se sobrou → Poupar o que sobrou (spoiler: não sobra nada)\n\nA lógica que funciona:\nSalário → **POUPAR primeiro** → Pagar contas → Gastar o que sobrou\n\n**Sua primeira separação:**\nHoje, separe qualquer valor da sua conta corrente para sua reserva de emergência. Pode ser R$10, R$50, R$100 — o valor não importa hoje. O que importa é o HÁBITO de separar ANTES de gastar.\n\n**Quanto separar?**\n- Se está endividado e apertado: R$10-50 por semana\n- Se está no zero a zero: 10% da renda mensal\n- Se tem folga: 20% da renda mensal\n- Se quer acelerar: 30%+\n\n**A meta de longo prazo é 20%.** Mas se você está em 0%, ir pra 5% já é revolução.\n\n**A ciência:** Present bias: seu cérebro sempre escolhe o prazer imediato sobre o benefício futuro. Quando o dinheiro sai AUTOMATICAMENTE no dia do pagamento, seu cérebro se adapta ao novo "salário disponível" em 2-3 meses. Pesquisa de Thaler e Benartzi mostrou que auto-enrollment em poupança aumentou participação de 37% para 86%.', 10);

  -- DAY 6
  INSERT INTO public.journey_days (journey_id, phase_id, day_number, title, card_content, estimated_minutes) VALUES
  (v_journey_id, v_phase1_id, 6, 'O dia sem gasto', E'Hoje o desafio é simples mas revelador: não gaste nenhum dinheiro por 24 horas. Zero. Nada. Nem um café.\n\n**Desafio — Dia de gasto zero:**\nRegras:\n- Contas fixas que vencem hoje não contam — pague normalmente\n- Qualquer gasto variável: ZERO\n- Sem iFood, sem café de rua, sem Uber, sem compra online\n- Coma o que tem em casa. Ande a pé ou de transporte com crédito\n\n**Por que esse exercício existe:**\nNão é sobre economizar R$30 em um dia. É sobre descobrir a relação que você tem com gastar. Observe:\n- Quantas vezes durante o dia sentiu vontade de comprar algo?\n- Qual foi o gatilho? (tédio, hábito, conforto, social)\n- Como se sentiu resistindo?\n\nSe achou muito difícil: isso revela o quanto gastar virou automático. Exatamente como o detox digital revelou o vício no celular, o dia sem gasto revela o "vício" em consumir.\n\n**Micro-aula — A regra das 48 horas:**\nPara qualquer compra não-essencial acima de R$50: espere 48 horas. Pesquisa mostra que o impulso de compra dura em média 24-48h. Passado esse período, a maioria das pessoas decide que não precisa do item.', 10);

  -- DAY 7
  INSERT INTO public.journey_days (journey_id, phase_id, day_number, title, card_content, is_review_day, estimated_minutes) VALUES
  (v_journey_id, v_phase1_id, 7, 'Review semanal #1', E'Primeira semana completa. Hora de olhar os dados e tirar conclusões.\n\n**Review semanal financeiro:**\n1. Total gasto na semana: R$___\n2. Top 3 categorias de gasto\n3. Gasto que mais te surpreendeu\n4. Gasto que poderia ter evitado facilmente\n5. Quanto separou para reserva essa semana: R$___\n6. Nota de consciência financeira (1-10)\n7. Uma coisa que vai fazer diferente na semana que vem\n\n**Reflexão da Semana 1:**\nSe você registrou gastos todos os dias, já está fazendo mais que 47% dos jovens brasileiros que não fazem nenhum controle. Se separou qualquer valor para poupança — mesmo R$10 — já começou algo que 55% dos Gen Z não têm.\n\n**🏆 Badge: "Olhos Abertos" — Semana 1 completa**', true, 15);

  -- DAY 8
  INSERT INTO public.journey_days (journey_id, phase_id, day_number, title, card_content, estimated_minutes) VALUES
  (v_journey_id, v_phase2_id, 8, 'O Fator Latte: onde seu dinheiro escorre', E'Ninguém quebra gastando R$3.000 de uma vez. As pessoas quebram gastando R$15 por dia, todos os dias, sem perceber.\n\n**NOVO HÁBITO — Fator Latte:**\nRegistre todo gasto "pequeno" e recorrente do dia com valor exato.\n\nExemplos comuns:\n| Gasto | Valor | Frequência | Custo mensal | Custo anual |\n|-------|-------|------------|-------------|-------------|\n| Café padaria | R$7 | Diário | R$210 | R$2.520 |\n| iFood almoço | R$28 | 3x/semana | R$336 | R$4.032 |\n| Uber curta | R$12 | 4x/semana | R$192 | R$2.304 |\n| Snack/lanche | R$10 | Diário | R$300 | R$3.600 |\n\n**Preencha com SEUS gastos.** Use os dados da semana 1.\n\n**A revelação:** A maioria dos jovens descobre que gasta R$500-1.500/mês em "coisinhas". Isso é R$6.000-18.000 por ano.\n\n**Exercício de perspectiva:**\nPegue seu total mensal de "fator latte" e multiplique por 12. O que poderia fazer com esse dinheiro?\n- ___ meses de reserva de emergência\n- Viagem para ___\n- Investido a 10%/ano por 10 anos = R$___\n\nNão é pra parar de tomar café. É pra VER o custo real das suas escolhas diárias.', 15);

  -- DAY 9
  INSERT INTO public.journey_days (journey_id, phase_id, day_number, title, card_content, estimated_minutes) VALUES
  (v_journey_id, v_phase2_id, 9, 'Juros compostos: a força mais poderosa', E'Einstein teria dito: "Juros compostos são a oitava maravilha do mundo. Quem entende, ganha. Quem não entende, paga."\n\n**Juros simples vs compostos:**\n- Simples: R$1.000 a 10%/ano. Ganha R$100/ano. Em 10 anos: R$2.000.\n- Compostos: R$1.000 a 10%/ano. Em 10 anos: R$2.594. Em 20 anos: R$6.727. Em 30 anos: R$17.449.\n\n**A variável mais importante: TEMPO.**\nDois amigos:\n- **Lucas** investe R$200/mês dos 22 aos 32 (10 anos, R$24.000 total)\n- **Pedro** investe R$200/mês dos 32 aos 62 (30 anos, R$72.000 total)\n\nAos 62, com retorno de 10%/ano:\n- Lucas (começou cedo): ~R$680.000\n- Pedro (investiu 3x mais): ~R$430.000\n\nLucas investiu R$24.000. Pedro investiu R$72.000. Lucas tem R$250.000 A MAIS. Porque começou 10 anos antes.\n\n**O lado sombrio:**\nCartão de crédito no Brasil cobra 400-500% ao ano no rotativo. Uma dívida de R$1.000 no rotativo por 12 meses pode virar R$5.000+.\n\n**Regra de ouro:** Juros compostos devem SEMPRE trabalhar A SEU FAVOR (investindo), NUNCA contra você (dívida rotativa).', 10);

  -- DAY 10
  INSERT INTO public.journey_days (journey_id, phase_id, day_number, title, card_content, estimated_minutes) VALUES
  (v_journey_id, v_phase2_id, 10, 'Seu orçamento: a regra 50/30/20', E'Chegou a hora de montar SEU orçamento. Sem planilha de 47 categorias. Três números. É isso.\n\n**NOVO HÁBITO — Orçamento semanal:**\nTodo domingo (ou segunda de manhã), planeje os gastos da semana.\n\n**A Regra 50/30/20:**\nPegue sua renda líquida mensal e divida:\n\n| Categoria | % | Exemplos |\n|-----------|---|----------|\n| **Necessidades** | 50% | Aluguel, mercado, transporte, saúde, contas |\n| **Desejos** | 30% | Delivery, streaming, bares, roupas, lazer |\n| **Poupança/Dívidas** | 20% | Reserva, investimentos, quitar dívidas |\n\n**Exemplo prático (renda R$3.000):**\n- Necessidades (50%): R$1.500\n- Desejos (30%): R$900\n- Poupança (20%): R$600\n\n**Se suas necessidades passam de 50%:**\nAjuste: 60/20/20 ou até 70/15/15. O importante é SEMPRE manter algo para poupança.\n\n**Se tem dívidas:**\nA categoria "Poupança" vira "Poupança + Dívidas". Prioridade: (1) reserva mínima de R$500-1.000 → (2) quitar dívidas com juros altos → (3) expandir reserva → (4) investir.\n\n**Seu orçamento semanal:**\nDivida o valor mensal de "Desejos" por 4. Esse é seu budget semanal. Quando acabou, acabou.', 20);

  -- DAY 11
  INSERT INTO public.journey_days (journey_id, phase_id, day_number, title, card_content, estimated_minutes) VALUES
  (v_journey_id, v_phase2_id, 11, 'O inimigo #1: cartão de crédito', E'Cartão de crédito é a ferramenta mais perigosa nas mãos de quem não tem controle financeiro. 39% das dívidas dos brasileiros começam nele.\n\n**Diagnóstico do cartão:**\n- Limite total: R$___\n- Fatura atual: R$___\n- % do limite usado: ___%\n- Paga fatura integral ou mínimo?\n- Parcelamentos ativos: ___\n\n**As 3 regras de ouro do cartão:**\n1. **SEMPRE pague a fatura integral.** O rotativo cobra 400-500% ao ano. Pagar o mínimo é a armadilha mais cara do sistema financeiro.\n2. **Limite não é renda.** R$5.000 de limite não significa que você TEM R$5.000.\n3. **Parcele com cautela.** Se o total de parcelas futuras passa de 30% da sua renda, pare de parcelar.\n\n**Se já está com dívida de cartão:**\n- Ligue para o banco e negocie (SEMPRE é possível negociar)\n- Peça redução de juros ou parcelamento da fatura\n- Se possível, faça portabilidade para crédito pessoal com juros menores\n\n**Exercício:** Some todas as suas parcelas ativas no cartão. Esse número é dinheiro que você JÁ DEVE mas ainda não sentiu.', 15);

  -- DAY 12
  INSERT INTO public.journey_days (journey_id, phase_id, day_number, title, card_content, estimated_minutes) VALUES
  (v_journey_id, v_phase2_id, 12, 'Automação: o hack que muda tudo', E'Se você depende de disciplina para poupar, vai falhar. Disciplina acaba. O sistema tem que funcionar mesmo quando você está cansado ou com vontade de gastar. A resposta é automação.\n\n**Tire o humano da equação:**\nQuando auto-enrollment em poupança foi implementado, participação saltou de 37% para 86%. As pessoas não ficaram mais disciplinadas — o sistema mudou.\n\n**Seu sistema de automação (configure HOJE):**\n\n**Dia do pagamento (D+0):**\n1. Transferência automática de ___% para reserva de emergência\n2. Pagamento automático de contas fixas\n3. O que sobra = seus gastos variáveis do mês\n\n**Configure no app do banco:**\n- Agendamento recorrente: transferência para caixinha/poupança\n- Data: mesmo dia do pagamento (ou D+1)\n- Valor: comece com o que conseguir (mínimo R$50)\n- Débito automático para contas fixas\n\n**A psicologia:** Quando o dinheiro sai automaticamente, seu cérebro se adapta em 2-3 meses ao "novo salário". Você não sente falta do que nunca chegou a ver como disponível.\n\n**Analogia com o detox digital:** É o mesmo princípio do "phone out of bedroom" — em vez de resistir à tentação, você remove a tentação do ambiente.', 15);

  -- DAY 13
  INSERT INTO public.journey_days (journey_id, phase_id, day_number, title, card_content, is_cliff_day, motivational_note, estimated_minutes) VALUES
  (v_journey_id, v_phase2_id, 13, 'THE CLIFF: quando a motivação some', E'Se você está pensando "tá chato registrar gasto todo dia" ou "semana que vem eu organizo" — parabéns, você está no CLIFF. Exatamente onde a maioria desiste.\n\n**O padrão THE CLIFF:**\n- Dias 1-5: Empolgação alta, tudo é novidade\n- Dias 8-14: Empolgação cai, sistema parece trabalhoso, resultados ainda não são visíveis\n- A voz interna: "Não faz diferença registrar R$6 de café", "Eu mereço gastar", "Depois eu organizo"\n\n**Se você está sentindo isso:**\nÉ normal. O CLIFF não significa que o sistema não funciona — significa que você está saindo da fase de motivação e entrando na fase de disciplina.\n\n**Mínimo inegociável hoje:**\nSe registrar todos os gastos parece demais, faça APENAS:\n1. Registre os 3 maiores gastos do dia\n2. Olhe o saldo da conta antes de dormir (30 segundos)\n3. Mantenha a automação rodando (ela não precisa de motivação)\n\n**Lembre:** A automação é seu melhor amigo porque funciona mesmo quando você não está motivado. É por isso que configuramos ela primeiro.', true, 'Muita gente desiste aqui nos dias 10-14. O desconforto é temporário. A automação continua rodando — confie no sistema.', 10);

  -- DAY 14
  INSERT INTO public.journey_days (journey_id, phase_id, day_number, title, card_content, is_review_day, estimated_minutes) VALUES
  (v_journey_id, v_phase2_id, 14, 'Review semanal #2', E'Duas semanas. Você tem dados de 14 dias de gastos, um orçamento montado e automação configurada (ou planejada). Isso é mais estrutura financeira do que 82% dos brasileiros têm.\n\n**Review semanal #2:**\n1. Total gasto na semana: R$___\n2. Comparado com semana 1: ↑ / ↓ / =\n3. Segui meu orçamento semanal? Sim / Parcialmente / Não\n4. Maior "vazamento" da semana\n5. Automação funcionando? Sim / Ainda não configurei\n6. Saldo da reserva de emergência: R$___\n7. Nota de consciência financeira (1-10)\n\n**Comparação com o baseline (Dia 1):**\n- Consciência sobre gastos: antes ___/10, agora ___/10\n- Sinto que tenho mais controle? Sim / Não / Um pouco\n\n**🏆 Badge: "Sistema Montado" — Semana 2 completa**', true, 15);

  -- DAY 15
  INSERT INTO public.journey_days (journey_id, phase_id, day_number, title, card_content, estimated_minutes) VALUES
  (v_journey_id, v_phase3_id, 15, 'O grande corte', E'Duas semanas de dados. Chegou a hora de pegar a tesoura. Não vamos cortar tudo — vamos cortar o que não vale a pena.\n\n**Confirme automação ativa:**\nSe ainda não configurou a transferência automática, HOJE é o dia. Sem desculpas. Abra o app do banco e configure. Qualquer valor.\n\n**Exercício — Os 3 cortes:**\nCom base em 2 semanas de dados, identifique 3 gastos para reduzir (não eliminar):\n\n| Gasto atual | Valor/mês | Alternativa | Novo valor | Economia |\n|-------------|-----------|-------------|------------|----------|\n| Ex: iFood 4x/sem | R$480 | Cozinhar 2x, iFood 2x | R$240 | R$240 |\n\n**Onde cortar primeiro (maior impacto, menor dor):**\n1. **Delivery** — De 5x/semana para 2-3x. Economiza R$200-400/mês\n2. **Transporte por app** — Substituir 50% por transporte público\n3. **Compras por impulso** — Aplicar regra de 48h em tudo acima de R$50\n4. **Assinaturas esquecidas** — Verificar em breve (Dia 22)\n\n**Regra:** Cada real economizado vai direto para a reserva de emergência. Não é economia se gastou em outra coisa.', 15);

  -- DAY 16
  INSERT INTO public.journey_days (journey_id, phase_id, day_number, title, card_content, estimated_minutes) VALUES
  (v_journey_id, v_phase3_id, 16, 'Se você tem dívidas: o plano de ataque', E'Se não tem dívidas, leia mesmo assim — é prevenção. Se tem, hoje é o dia de encarar de frente.\n\n**Mapeamento completo de dívidas:**\n| Dívida | Valor total | Juros/mês | Parcela | Prioridade |\n|--------|------------|-----------|---------|------------|\n| Cartão rotativo | R$___ | ___% | R$___ | 🔴 |\n| Cheque especial | R$___ | ___% | R$___ | 🔴 |\n| Empréstimo pessoal | R$___ | ___% | R$___ | 🟡 |\n| Parcelas sem juros | R$___ | 0% | R$___ | 🟢 |\n\n**Prioridades:**\n- 🔴 Rotativo e cheque especial → juros ABSURDOS (300-500%/ano). Toda energia aqui primeiro\n- 🟡 Empréstimos com juros médios → negociar taxa\n- 🟢 Parcelas sem juros → manter regularidade\n\n**Método Avalanche (matematicamente superior):**\nPague mínimo de todas. Dinheiro extra → dívida com MAIOR taxa de juros.\n\n**Método Bola de Neve (psicologicamente motivador):**\nPague mínimo de todas. Dinheiro extra → MENOR dívida.\n\n**Qual escolher?** Pesquisa mostra que consistência importa mais que o método.\n\n**Ação imediata (se tem dívida de cartão rotativo):**\n1. Ligue para o banco HOJE\n2. Peça para parcelar a fatura\n3. Negocie redução de taxa', 20);

  -- DAY 17
  INSERT INTO public.journey_days (journey_id, phase_id, day_number, title, card_content, estimated_minutes) VALUES
  (v_journey_id, v_phase3_id, 17, 'Reserva de emergência: sua primeira fortaleza', E'Reserva de emergência não é investimento. Não é poupança para viagem. É o colchão que impede que um imprevisto destrua sua vida financeira inteira.\n\n**O que NÃO é emergência:**\n- iFood porque deu preguiça ❌\n- Promoção imperdível ❌\n- Viagem de última hora ❌\n\n**O que É emergência:**\n- Perda de renda ✅\n- Problema de saúde urgente ✅\n- Conserto essencial ✅\n\n**Quanto ter:**\n- Meta mínima (Nível 1): 1 mês de despesas essenciais\n- Meta intermediária: 3 meses\n- Meta ideal: 6 meses\n\n**Onde guardar:**\n- ✅ CDB liquidez diária (100% CDI) — rende mais que poupança, pode sacar a qualquer momento\n- ✅ Tesouro Selic — super seguro, liquidez D+1\n- ✅ Conta remunerada (Nubank, Inter, etc.)\n- ❌ Poupança tradicional — rende menos que inflação\n- ❌ Ações, cripto, fundos — reserva NÃO pode oscilar\n\n**Ação de hoje:**\nConfira quanto tem na reserva e defina sua meta do mês.', 10);

  -- DAY 18
  INSERT INTO public.journey_days (journey_id, phase_id, day_number, title, card_content, estimated_minutes) VALUES
  (v_journey_id, v_phase3_id, 18, 'Tracker de reserva: visualize o progresso', E'Progresso visível é o combustível da disciplina. Quando você VÊ o número crescendo, o cérebro libera dopamina — a mesma que antes vinha de gastar. Só que dessa vez está te construindo.\n\n**NOVO — Tracker de reserva:**\nA cada dia (ou semana), registre o saldo da sua reserva no dashboard.\n\n**Marcos motivacionais:**\n- [ ] R$100 — "Comecei"\n- [ ] R$500 — "Primeira fortaleza"\n- [ ] R$1.000 — "Quatro dígitos"\n- [ ] 1 mês de despesas — "Colchão mínimo"\n- [ ] 3 meses de despesas — "Segurança real"\n\n**A ciência — Gamificação financeira:**\nPesquisa mostra que visualizar progresso de poupança aumenta motivação e consistência. Quando substituímos a dopamina de gastar pela dopamina de ver a reserva crescer, estamos reconfigurando o sistema de recompensa.\n\n**Dica prática:** Coloque o saldo da reserva como widget na home do celular. Toda vez que for abrir o app de delivery, você vê quanto tem guardado. Funciona como friction positiva.', 10);

  -- DAY 19
  INSERT INTO public.journey_days (journey_id, phase_id, day_number, title, card_content, estimated_minutes) VALUES
  (v_journey_id, v_phase3_id, 19, 'Renegociando sua vida: gastos fixos', E'Gastos variáveis são onde a maioria foca (delivery, café). Mas os gastos FIXOS são onde está o dinheiro grande. Reduzir um gasto fixo em R$50 economiza R$600/ano sem esforço nenhum.\n\n**Exercício — Renegociação de fixos:**\n\n| Gasto fixo | Valor atual | Alternativa | Possível economia |\n|------------|-------------|-------------|-------------------|\n| Plano celular | R$___ | Plano menor ou pré-pago? | R$___/mês |\n| Internet | R$___ | Negociar com operadora? | R$___/mês |\n| Streaming | R$___ | Manter apenas 1? Dividir conta? | R$___/mês |\n| Seguro | R$___ | Cotar com outras? | R$___/mês |\n| Academia | R$___ | Plano mais barato? | R$___/mês |\n\n**Scripts de negociação:**\n- **Celular:** "Estou avaliando meu plano e vi que a [concorrente] oferece [plano] por R$[valor]. Vocês conseguem cobrir?"\n- **Internet:** "Meu contrato vence em [data]. Estou cotando com outras operadoras. Existe condição melhor?"\n\n**Regra:** Toda economia de gasto fixo vai direto para a reserva.', 20);

  -- DAY 20
  INSERT INTO public.journey_days (journey_id, phase_id, day_number, title, card_content, estimated_minutes) VALUES
  (v_journey_id, v_phase3_id, 20, 'Compras inteligentes: como gastar melhor', E'Finanças pessoais não é sobre nunca gastar. É sobre gastar COM INTENÇÃO.\n\n**Princípios de compra inteligente:**\n\n**1. Custo por uso (CPU):**\nAntes de comprar, divida o preço pelo número de vezes que vai usar:\n- Tênis de R$400 usado 200x = R$2/uso ✅\n- Camisa de R$200 usada 3x = R$67/uso ❌\n- Netflix R$40/mês usada 20h = R$2/hora ✅\n- App de R$30/mês usado 1x = R$30/uso ❌\n\n**2. Regra das 48h para compras acima de R$50:**\nColoque no carrinho, espere 48h, decida depois.\n\n**3. "Uma entra, uma sai":**\nPara cada item novo, um antigo precisa sair. Evita acumulação e força reflexão.\n\n**4. Pesquise SEMPRE:**\n- Use Buscapé, Zoom, Google Shopping para comparar preços\n- Ative alertas de preço para itens que quer\n- Black Friday: compare com preço histórico\n- Cashback: use apps como Méliuz, Ame, PicPay em compras que já faria', 10);

  -- DAY 21
  INSERT INTO public.journey_days (journey_id, phase_id, day_number, title, card_content, is_review_day, estimated_minutes) VALUES
  (v_journey_id, v_phase3_id, 21, 'Review semanal #3', E'Três semanas. Você tem orçamento, automação rodando, reserva de emergência iniciada, e consciência que não tinha 21 dias atrás. Está no top 20% dos jovens brasileiros em organização financeira.\n\n**Review semanal #3:**\n1. Total gasto na semana: R$___\n2. Dentro do orçamento semanal?\n3. Quanto foi para a reserva essa semana: R$___\n4. Saldo total da reserva: R$___\n5. Conseguiu fazer os 3 cortes do Dia 15? Total / Parcial / Não\n6. Algum gasto fixo renegociado? Economia de R$___\n7. Nota de controle financeiro (1-10)\n\n**Marcos alcançados até aqui:**\n- [ ] Sei exatamente quanto gasto por mês\n- [ ] Tenho orçamento 50/30/20 (ou adaptado)\n- [ ] Automação de poupança configurada\n- [ ] Reserva de emergência iniciada (qualquer valor)\n- [ ] Registrei gastos por 3+ semanas consecutivas\n\n**🏆 Badge: "Reserva Iniciada" — Semana 3 completa**', true, 15);

  -- DAY 22
  INSERT INTO public.journey_days (journey_id, phase_id, day_number, title, card_content, estimated_minutes) VALUES
  (v_journey_id, v_phase4_id, 22, 'Auditoria de assinaturas', E'O brasileiro médio tem 3-5 assinaturas que paga sem usar regularmente. Hoje vamos encontrar e eliminar as que não valem a pena.\n\n**Auditoria completa de assinaturas:**\n\n| Serviço | Valor/mês | Última vez que usei | Uso mensal real | Manter? |\n|---------|-----------|--------------------|-----------------|---------|\n| Netflix | R$___ | ___ | ___h | S/N |\n| Spotify | R$___ | ___ | ___h | S/N |\n| Amazon Prime | R$___ | ___ | ___x | S/N |\n| Academia | R$___ | ___ | ___x | S/N |\n| iCloud/Google | R$___ | ___ | Essencial? | S/N |\n\n**Critério para manter:**\n- Uso pelo menos 3x por semana? → Considerar manter\n- Uso menos de 1x por semana? → Cancelar ou compartilhar\n- Não usei no último mês? → Cancelar imediatamente\n- Posso substituir por versão gratuita? → Substituir\n\n**Ação:** Cancele HOJE todo serviço que marcou "N". São 5 minutos por cancelamento que podem economizar centenas por ano.', 20);

  -- DAY 23
  INSERT INTO public.journey_days (journey_id, phase_id, day_number, title, card_content, estimated_minutes) VALUES
  (v_journey_id, v_phase4_id, 23, 'Receita extra: aumente o lado da entrada', E'Até agora focamos em gastar menos. Igualmente importante: ganhar mais. Existem dois lados do orçamento.\n\n**As duas alavancas do dinheiro:**\n1. **Gastar menos** — tem limite: não pode gastar menos que zero\n2. **Ganhar mais** — não tem teto\n\n**Ideias para renda extra (realistas para 20-25 anos):**\n- **Freelance na sua área:** Marketing, design, programação, escrita — Workana, 99Freelas, Fiverr\n- **Aulas/tutoria:** Idiomas, matérias, instrumento, treino\n- **Venda de itens:** O que tem em casa sem usar? OLX, Enjoei, Mercado Livre\n- **Habilidades rápidas:** Edição de vídeo/foto, gestão de redes sociais, planilhas\n- **Economia colaborativa:** Pesquisas remuneradas, cashback estratégico\n\n**Exercício da "habilidade monetizável":**\nListe 3 coisas que você sabe fazer melhor que a maioria ao seu redor. Alguém pagaria por isso?\n\n**Regra de ouro:** 100% da renda extra vai para: (1) quitar dívida, ou (2) reserva de emergência. NÃO é para aumentar o padrão de vida.', 15);

  -- DAY 24
  INSERT INTO public.journey_days (journey_id, phase_id, day_number, title, card_content, estimated_minutes) VALUES
  (v_journey_id, v_phase4_id, 24, 'Conversas sobre dinheiro', E'A maioria dos jovens brasileiros nunca teve uma conversa séria sobre dinheiro com alguém. Dinheiro é tabu, é "feio" falar sobre. Hoje quebramos esse silêncio.\n\n**Por que importa:**\nPesquisa mostra que contexto social e exposição a conversas sobre finanças são fatores determinantes no desenvolvimento de hábitos financeiros saudáveis — mais até do que autoconfiança financeira.\n\n**Exercício — Uma conversa real:**\nEscolha 1 pessoa (amigo, parceiro/a, familiar) e tenha UMA conversa sobre:\n- "Você sabe quanto gasta por mês?"\n- "Você tem reserva de emergência?"\n- "Como você lida com dinheiro no dia-a-dia?"\n\nNão é para julgar ou ensinar. É para normalizar o assunto. Se puder, compartilhe o que aprendeu nas últimas 3 semanas.\n\n**O efeito:** Falar sobre dinheiro abertamente reduz vergonha, cria accountability, e muitas vezes revela que TODO MUNDO está perdido — você não é exceção, é a regra.', 10);

  -- DAY 25
  INSERT INTO public.journey_days (journey_id, phase_id, day_number, title, card_content, estimated_minutes) VALUES
  (v_journey_id, v_phase4_id, 25, 'Seu dinheiro no futuro: o poder do tempo', E'Você tem entre 20 e 25 anos. O maior ativo financeiro que você possui não é dinheiro — é TEMPO.\n\n**Exercício de visualização:**\nSe investir R$200/mês a partir de HOJE, com retorno médio de 10%/ano:\n\n| Idade | Anos investindo | Total investido | Valor acumulado |\n|-------|----------------|-----------------|---|\n| 25 | 0 | R$0 | R$0 |\n| 30 | 5 | R$12.000 | ~R$15.600 |\n| 35 | 10 | R$24.000 | ~R$41.000 |\n| 45 | 20 | R$48.000 | ~R$153.000 |\n| 55 | 30 | R$72.000 | ~R$434.000 |\n| 65 | 40 | R$96.000 | ~R$1.170.000 |\n\n**R$200/mês = R$1.17 milhão aos 65 anos.** Juros compostos fizeram o resto.\n\nSe esperar 10 anos: ~R$434.000. Perdeu ~R$736.000 por esperar.\n\nNão precisa entender de ações ou cripto. Precisa entender UMA coisa: comece. O Nível 2 aborda investimentos — por enquanto, sua reserva em CDB ou conta remunerada já é sua primeira "aplicação".', 10);

  -- DAY 26
  INSERT INTO public.journey_days (journey_id, phase_id, day_number, title, card_content, estimated_minutes) VALUES
  (v_journey_id, v_phase4_id, 26, 'Protocolo anti-impulso', E'Compras por impulso são a versão financeira do scroll infinito: você não planejou, não precisa, mas o cérebro pede e a mão obedece.\n\n**Sistema anti-impulso (configure HOJE):**\n\n1. **Remova cartão salvo de tudo:** iFood, Amazon, Mercado Livre, Uber Eats — delete os dados do cartão. O simples ato de digitar o número toda vez adiciona 30 segundos de fricção. Pesquisa mostra que adicionar fricção reduz gastos impulsivos significativamente.\n\n2. **Desative notificações de promoção:** Shein, Amazon, Shopee, iFood — todas enviam push notifications projetadas para disparar desejo de compra.\n\n3. **"Lista antes de loja":** Nunca entre em mercado, shopping ou site de compras sem lista prévia. Compre APENAS o que está na lista.\n\n4. **Regra 10-10-10:** Antes de uma compra não-essencial: "Como vou me sentir sobre isso em 10 minutos? Em 10 horas? Em 10 dias?" Se para 10 dias é "nem vou lembrar", não compre.', 10);

  -- DAY 27
  INSERT INTO public.journey_days (journey_id, phase_id, day_number, title, card_content, estimated_minutes) VALUES
  (v_journey_id, v_phase4_id, 27, 'O que fazer com dinheiro que sobra', E'Eventualmente, por causa de bônus, freelance, 13° ou simplesmente porque seu sistema está funcionando, vai "sobrar" dinheiro. O que fazer com ele define se você constrói patrimônio ou volta à estaca zero.\n\n**Hierarquia do dinheiro extra:**\n\n**Passo 1:** Tem dívida com juros altos?\n→ SIM: 100% vai para quitar a dívida.\n→ NÃO: Passo 2.\n\n**Passo 2:** Tem reserva de pelo menos 3 meses?\n→ NÃO: Dinheiro extra vai para reserva.\n→ SIM: Passo 3.\n\n**Passo 3:** Reserva completa, sem dívidas.\n→ Agora sim: investir (Nível 2), antecipar metas, ou usar conscientemente.\n\n**A armadilha do "merecimento":**\n"Recebi bônus, MEREÇO gastar." Você merece. Mas o "eu do futuro" também merece.\n\n**Regra sugerida para dinheiro extra:** 50% reserva/investimento + 50% para você gastar como quiser, sem culpa.', 10);

  -- DAY 28
  INSERT INTO public.journey_days (journey_id, phase_id, day_number, title, card_content, is_review_day, estimated_minutes) VALUES
  (v_journey_id, v_phase4_id, 28, 'Review semanal #4', E'Última semana da jornada. Quatro reviews completos. Quatro semanas de dados. Você não é mais a mesma pessoa financeiramente.\n\n**Review semanal #4:**\n1. Total gasto na semana: R$___\n2. Dentro do orçamento? Sim / Não\n3. Saldo da reserva de emergência: R$___\n4. Dívidas reduzidas em R$___ desde o início\n5. Assinaturas canceladas: ___ | Economia: R$___/mês\n6. Automação funcionando sem intervenção? Sim / Não\n7. Nota de controle financeiro (1-10)', true, 15);

  -- DAY 29
  INSERT INTO public.journey_days (journey_id, phase_id, day_number, title, card_content, estimated_minutes) VALUES
  (v_journey_id, v_phase4_id, 29, 'Seu protocolo financeiro permanente', E'A jornada termina amanhã. Mas seu sistema financeiro é para sempre. Hoje vamos definir o que fica.\n\n**Protocolo permanente — escolha mínimo 7 para manter:**\n\n**DIÁRIO:**\n- [ ] Registrar gastos (pode simplificar: só os maiores ou usar app automático)\n- [ ] Pausa de 10s antes de gastos não-essenciais\n- [ ] Check noturno de 2 min (saldo + gastos)\n\n**SEMANAL:**\n- [ ] Orçamento da semana (domingo ou segunda)\n- [ ] Review financeiro semanal (15 min)\n\n**MENSAL:**\n- [ ] Pague-se primeiro no dia do pagamento (automático)\n- [ ] Revisão do orçamento 50/30/20 com dados reais\n- [ ] Verificar saldo da reserva e atualizar meta\n\n**TRIMESTRAL:**\n- [ ] Auditoria de assinaturas\n- [ ] Renegociação de gastos fixos\n- [ ] Ajustar % de poupança\n\n**O mínimo inegociável (se tudo mais falhar, mantenha ESTES 3):**\n1. 🔄 Automação de poupança no dia do pagamento\n2. 📊 Review semanal de 15 min\n3. 🚫 Nunca entrar no rotativo do cartão', 15);

  -- DAY 30
  INSERT INTO public.journey_days (journey_id, phase_id, day_number, title, card_content, estimated_minutes) VALUES
  (v_journey_id, v_phase4_id, 30, 'GRADUAÇÃO: Controle Total', E'30 dias. De zero controle para sistema completo. De não saber pra onde ia o dinheiro para orçamento, automação e reserva. Você fez o que 82% dos brasileiros não conseguem: tomou controle das suas finanças.\n\n**Transformação — Baseline vs. Hoje:**\n\n| Métrica | Dia 1 | Dia 30 |\n|---------|-------|--------|\n| Consciência financeira (1-10) | ___ | ___ |\n| Sabe pra onde vai cada real? | Não/Parcial | Sim |\n| Tem orçamento? | Não | Sim (50/30/20) |\n| Automação de poupança? | Não | Sim |\n| Reserva de emergência | R$___ | R$___ |\n| Dívidas | R$___ | R$___ |\n| Assinaturas canceladas | 0 | ___ |\n\n**O que você construiu em 30 dias:**\n- Sistema de registro e consciência de gastos\n- Orçamento funcional baseado em dados reais\n- Automação de poupança no dia do pagamento\n- Reserva de emergência iniciada\n- Protocolo anti-impulso e anti-dívida\n- Entendimento de juros compostos e o poder do tempo\n- Hábitos de revisão semanal\n\n**Próximos passos — Nível 2: "Faça Seu Dinheiro Trabalhar"**\nO Nível 1 foi sobre CONTROLE. Nível 2 é sobre CRESCIMENTO: investimentos básicos, construção de patrimônio, proteção financeira e múltiplas fontes de renda.\n\n**🏆 Badge Final: "Controle Total" — Jornada Nível 1 completa**\n**🔓 Desbloqueado: Nível 2 — "Faça Seu Dinheiro Trabalhar"**', 15);

  -- ============================================
  -- 3. Habit Templates
  -- ============================================

  INSERT INTO public.journey_habit_templates (journey_id, name, emoji, category, period, tracking_type, unit, initial_goal_value, start_day, end_day, frequency_type, days_of_week, goal_progression, canonical_key, sort_order) VALUES

  -- 1. Registrar gastos diários (Day 1 → end)
  (v_journey_id, 'Registrar gastos diários', '💰', 'finanças', 'evening', 'checkbox', 'none', NULL, 1, NULL, 'daily', '{0,1,2,3,4,5,6}', '[]', 'expense_tracking', 1),

  -- 2. Gasto consciente — pausa 10s (Day 1 → end)
  (v_journey_id, 'Gasto consciente', '🚫', 'finanças', 'morning', 'checkbox', 'none', NULL, 1, NULL, 'daily', '{0,1,2,3,4,5,6}', '[]', 'mindful_spending', 2),

  -- 3. Check financeiro noturno (Day 1 → end)
  (v_journey_id, 'Check financeiro noturno', '📊', 'finanças', 'evening', 'checkbox', 'none', NULL, 1, NULL, 'daily', '{0,1,2,3,4,5,6}', '[]', 'financial_check', 3),

  -- 4. Pague-se primeiro (Day 5 → end)
  (v_journey_id, 'Pague-se primeiro', '🏦', 'finanças', 'morning', 'checkbox', 'none', NULL, 5, NULL, 'daily', '{0,1,2,3,4,5,6}', '[]', 'pay_yourself_first', 4),

  -- 5. Fator latte — registrar pequenos gastos (Day 8 → end)
  (v_journey_id, 'Fator latte', '☕', 'finanças', 'evening', 'number', 'custom', NULL, 8, NULL, 'daily', '{0,1,2,3,4,5,6}', '[]', 'latte_factor', 5),

  -- 6. Orçamento semanal (Day 10 → end, weekly on Sunday)
  (v_journey_id, 'Orçamento semanal', '📋', 'finanças', 'morning', 'checkbox', 'none', NULL, 10, NULL, 'weekly', '{0}', '[]', 'weekly_budget', 6),

  -- 7. Automação ativa (Day 15 → end)
  (v_journey_id, 'Automação ativa', '🔄', 'finanças', 'morning', 'checkbox', 'none', NULL, 15, NULL, 'daily', '{0,1,2,3,4,5,6}', '[]', 'savings_automation', 7),

  -- 8. Meta de reserva — tracker de saldo (Day 18 → end)
  (v_journey_id, 'Meta de reserva', '🎯', 'finanças', 'evening', 'number', 'custom', NULL, 18, NULL, 'daily', '{0,1,2,3,4,5,6}', '[]', 'emergency_fund_tracker', 8),

  -- 9. Auditoria de assinaturas (Day 22 — one_time)
  (v_journey_id, 'Auditoria de assinaturas', '🧹', 'finanças', 'morning', 'checkbox', 'none', NULL, 22, 22, 'one_time', '{0,1,2,3,4,5,6}', '[]', NULL, 9),

  -- 10. Review semanal financeiro (Day 7 → end, weekly on Sunday)
  (v_journey_id, 'Review semanal financeiro', '📊', 'finanças', 'evening', 'checkbox', 'none', NULL, 7, NULL, 'weekly', '{0}', '[]', 'weekly_financial_review', 10);

END $$;
