-- ============================================
-- SEED: Finances L2 — "Faça Seu Dinheiro Trabalhar"
-- ============================================
-- NOTE: The journeys row for 'finances-l2' already exists
-- from 20260218000001_seed_digital_detox_l1.sql.
-- This migration seeds phases, days, and habit templates only.

DO $$
DECLARE
  v_journey_id uuid;
  v_phase1_id uuid;
  v_phase2_id uuid;
  v_phase3_id uuid;
  v_phase4_id uuid;
BEGIN
  SELECT id INTO v_journey_id FROM public.journeys WHERE slug = 'finances-l2';

  -- ============================================
  -- 1. Phases
  -- ============================================

  INSERT INTO public.journey_phases (journey_id, phase_number, title, subtitle, description, day_start, day_end, badge_illustration_key, badge_name)
  VALUES (v_journey_id, 1, 'FUNDAMENTOS', 'Aprenda o jogo', E'Entender os conceitos essenciais: renda fixa vs variável, inflação, CDI, Selic, perfil de investidor. Desmistificar o vocabulário que afasta 90% das pessoas.', 1, 7, 'finances-l2-phase-1', 'Vocabulário Financeiro')
  RETURNING id INTO v_phase1_id;

  INSERT INTO public.journey_phases (journey_id, phase_number, title, subtitle, description, day_start, day_end, badge_illustration_key, badge_name)
  VALUES (v_journey_id, 2, 'RENDA FIXA', 'Sua base sólida', E'Dominar os instrumentos de renda fixa: Tesouro Direto (Selic, IPCA+, Prefixado), CDB, LCI/LCA. Fazer o primeiro investimento real.', 8, 14, 'finances-l2-phase-2', 'Primeiro Investimento')
  RETURNING id INTO v_phase2_id;

  INSERT INTO public.journey_phases (journey_id, phase_number, title, subtitle, description, day_start, day_end, badge_illustration_key, badge_name)
  VALUES (v_journey_id, 3, 'RENDA VARIÁVEL', 'Acelere o crescimento', E'Introdução a ETFs, ações, fundos imobiliários. Montar a primeira carteira diversificada. Entender risco e volatilidade.', 15, 22, 'finances-l2-phase-3', 'Carteira Montada')
  RETURNING id INTO v_phase3_id;

  INSERT INTO public.journey_phases (journey_id, phase_number, title, subtitle, description, day_start, day_end, badge_illustration_key, badge_name)
  VALUES (v_journey_id, 4, 'SISTEMA COMPLETO', 'Sua máquina de patrimônio', E'Automação de aportes, rebalanceamento, múltiplas fontes de renda, proteção patrimonial e visão de longo prazo.', 23, 30, 'finances-l2-phase-4', 'Dinheiro Trabalhando')
  RETURNING id INTO v_phase4_id;

  -- ============================================
  -- 2. Journey Days (30 days)
  -- ============================================

  -- DAY 1
  INSERT INTO public.journey_days (journey_id, phase_id, day_number, title, card_content, estimated_minutes) VALUES
  (v_journey_id, v_phase1_id, 1, 'Revisão + reset de mentalidade', E'Você concluiu o Nível 1: tem controle sobre seus gastos, orçamento rodando e reserva iniciada. Agora vamos fazer seu dinheiro trabalhar POR você.\n\n**Check de pré-requisitos:**\nAntes de continuar, confirme:\n- [ ] Orçamento 50/30/20 rodando por 30+ dias\n- [ ] Automação de poupança ativa no dia do pagamento\n- [ ] Reserva de emergência mínima de R$1.000\n- [ ] Zero dívida de cartão rotativo/cheque especial\n- [ ] Registro de gastos regular\n\nSe algum item está em falso: volte ao Nível 1 e resolva antes de prosseguir. Investir sem base é como construir um prédio sem fundação.\n\n**5 verdades sobre investir:**\n1. **Você NÃO precisa de muito dinheiro.** Tesouro Direto começa com R$30. ETFs com ~R$10.\n2. **Investir NÃO é day trade.** Day trade é especulação — 97% perdem dinheiro (estudo FGV). Investir é alocar capital para o LONGO PRAZO.\n3. **Você NÃO precisa ser expert.** Tesouro Selic + IPCA+ + 1 ETF bate 90% das estratégias sofisticadas.\n4. **Não existe investimento sem risco.** Nem a poupança (perde da inflação). A questão é escolher o risco compatível com seus objetivos.\n5. **O melhor momento para começar é AGORA.** O custo de esperar é maior que o custo de começar pequeno.', 15);

  -- DAY 2
  INSERT INTO public.journey_days (journey_id, phase_id, day_number, title, card_content, estimated_minutes) VALUES
  (v_journey_id, v_phase1_id, 2, 'O glossário essencial: 15 termos que mudam tudo', E'O maior obstáculo para 90% das pessoas não é falta de dinheiro — é o vocabulário. Hoje vamos traduzir.\n\n**Os 15 termos que você PRECISA saber:**\n\n**Selic** — Taxa básica de juros do Brasil, definida pelo Banco Central. Referência para tudo no mercado. Selic sobe → renda fixa rende mais.\n\n**CDI** — Taxa entre bancos, muito próxima da Selic (~0,1% de diferença). "100% do CDI" ≈ Selic.\n\n**IPCA** — Inflação oficial do Brasil. Seu investimento precisa render MAIS que o IPCA para ganho real.\n\n**Rendimento real** — Retorno acima da inflação. 12% de rendimento - 5% de inflação = ~7% real.\n\n**Liquidez** — Velocidade para transformar investimento em dinheiro na conta. Diária = saca a qualquer hora.\n\n**Renda fixa** — Retorno previsível: Tesouro Direto, CDB, LCI/LCA. Menor risco.\n\n**Renda variável** — Retorno varia: ações, ETFs, FIIs. Maior risco, maior potencial.\n\n**Tesouro Direto** — Plataforma do governo para vender títulos públicos. Investimento mais seguro do Brasil.\n\n**CDB** — Você empresta dinheiro a um banco e recebe juros. Protegido pelo FGC até R$250k.\n\n**FGC** — Seguro que protege CDBs, LCIs e LCAs até R$250k por CPF por banco.\n\n**ETF** — Fundo que replica um índice. BOVA11 = maiores empresas BR. IVVB11 = 500 maiores dos EUA.\n\n**Diversificação** — Espalhar investimentos para reduzir risco. O único "almoço grátis".\n\n**Aporte** — Cada novo investimento. Aporte mensal = investir todo mês, sem tentar acertar o timing.\n\n**Volatilidade** — Oscilação de preço. Não é perda — só perde se vender na baixa.\n\n**Tabela regressiva de IR** — IR sobre renda fixa diminui com o tempo: 22,5% (até 180d) → 15% (acima de 720d).', 20);

  -- DAY 3
  INSERT INTO public.journey_days (journey_id, phase_id, day_number, title, card_content, estimated_minutes) VALUES
  (v_journey_id, v_phase1_id, 3, 'Seu perfil de investidor', E'Antes de investir um real, você precisa saber quem é como investidor. Não existe investimento "bom" ou "ruim" — existe certo ou errado pro seu perfil.\n\n**NOVO HÁBITO — Educação financeira diária:**\n15 minutos por dia consumindo conteúdo sobre investimentos. Podcast, vídeo, artigo ou livro. Sugestões: Me Poupe, Primo Rico, Investidor Sardinha, PrimoCast, "Psicologia Financeira" (Morgan Housel).\n\n**Os 3 perfis:**\n\n🟢 **Conservador** — Prioriza segurança. Aceita retornos menores. Carteira: 80-100% renda fixa.\n\n🟡 **Moderado** — Equilíbrio entre segurança e crescimento. Carteira: 60-70% renda fixa + 30-40% variável.\n\n🔴 **Arrojado** — Busca crescimento máximo no longo prazo. Aceita oscilações. Carteira: 30-50% fixa + 50-70% variável.\n\n**Para você (20-25 anos):** Provavelmente moderado a arrojado. TEMPO é seu maior ativo — se o mercado cair 30%, você tem 30-40 anos para recuperar.\n\n**Mas atenção:** Perfil não é só idade — é temperamento. Se queda de 20% te faz vender tudo em pânico às 3h da manhã, você NÃO é arrojado.\n\n**Teste rápido:** Investiu R$10.000 e caiu para R$7.500 (-25%). O que faz?\nA) Vendo tudo → Conservador\nB) Fico ansioso mas espero → Moderado\nC) Invisto mais, está em promoção → Arrojado', 15);

  -- DAY 4
  INSERT INTO public.journey_days (journey_id, phase_id, day_number, title, card_content, estimated_minutes) VALUES
  (v_journey_id, v_phase1_id, 4, 'A pirâmide de investimentos', E'Existe uma ORDEM certa para investir. Ignorar essa ordem é o erro #1 de quem começa.\n\n**A Pirâmide Financeira (a legítima):**\n\n5. ESPECULAÇÃO (topo) — Cripto, day trade, anjo. Máx 5%, só se sobrar.\n4. RENDA VARIÁVEL — ETFs, ações, FIIs. 20-50% da carteira.\n3. RENDA FIXA DE CRESCIMENTO — Tesouro IPCA+, CDB longo prazo. 20-40%.\n2. BASE SEGURA — Tesouro Selic, CDB DI. Liquidez diária, reserva de emergência. 20-30%.\n1. ZERO DÍVIDAS (base) — Pré-requisito absoluto.\n\n**A ORDEM:**\n1. **Zero dívidas caras** → Rotativo/cheque especial? Pare tudo e quite primeiro.\n2. **Reserva de emergência** → 3-6 meses em Tesouro Selic ou CDB liquidez diária.\n3. **Renda fixa de crescimento** → Tesouro IPCA+, CDBs médio/longo prazo.\n4. **Renda variável** → ETFs, ações, FIIs — para longo prazo.\n5. **Especulação** → MÁXIMO 5% e só se todo o resto está coberto.\n\n**Regra:** Nunca avance para o nível acima sem ter o de baixo resolvido. Comprar ações com dívida de cartão é como colocar o telhado antes das paredes.', 15);

  -- DAY 5
  INSERT INTO public.journey_days (journey_id, phase_id, day_number, title, card_content, estimated_minutes) VALUES
  (v_journey_id, v_phase1_id, 5, 'Onde abrir conta e começar', E'Para investir além da poupança, você precisa de uma corretora. A boa notícia: é grátis, leva 5 minutos e não precisa sair de casa.\n\n**NOVO HÁBITO — Aporte mensal:**\nRegistre todo valor investido no mês. O objetivo é criar consistência de aporte, não valor absoluto.\n\n**Corretora vs Banco:**\n- **Banco digital (Nubank, Inter, C6):** Conta gratuita + investimentos integrados. Boa opção para começar.\n- **Corretora independente (XP, Rico, Clear, BTG):** Maior variedade, melhores taxas em renda fixa.\n\n**Recomendação para iniciantes:** Se já usa Nubank ou Inter, comece por lá. Cobre 90% do que precisa.\n\n**Checklist da corretora:**\n- [ ] Taxa zero para Tesouro Direto?\n- [ ] Taxa zero para compra de ETFs?\n- [ ] Plataforma mobile funcional?\n- [ ] CDBs de diferentes emissores?\n\n**Ação de hoje:** Se não tem corretora, abra uma HOJE. Se já tem, faça login e explore a plataforma de investimentos.', 15);

  -- DAY 6
  INSERT INTO public.journey_days (journey_id, phase_id, day_number, title, card_content, estimated_minutes) VALUES
  (v_journey_id, v_phase1_id, 6, 'Inflação: o imposto invisível', E'Seu dinheiro está perdendo valor AGORA MESMO. R$100 de 2020 compram o equivalente a ~R$75 em 2026. Isso é inflação.\n\n**Inflação em números reais:**\n- IPCA médio dos últimos 5 anos: ~5-6% ao ano\n- Poupança rende ~8,3% ao ano (Selic a 15%) → rendimento real de ~2-3%\n- CDB 100% CDI rende ~15% bruto → ~12,5% líquido → rendimento real de ~7%\n- Tesouro IPCA+ garante rendimento ACIMA da inflação por definição\n\n**Traduzindo pro dia-a-dia:**\n- Almoço de R$20 em 2020 → R$28 em 2026\n- Aluguel de R$1.500 em 2020 → R$2.100 em 2026\n- Seu salário provavelmente não subiu na mesma proporção\n\n**A lição:** Qualquer investimento que rende MENOS que a inflação está te fazendo PERDER dinheiro em termos reais. A poupança frequentemente entra nessa categoria.\n\n**Exercício:** Quanto tem na poupança? R$___. Se migrasse para CDB 100% CDI, a diferença em 1 ano seria de ~R$___ a mais. Em 10 anos, ~R$___.', 15);

  -- DAY 7
  INSERT INTO public.journey_days (journey_id, phase_id, day_number, title, card_content, is_review_day, estimated_minutes) VALUES
  (v_journey_id, v_phase1_id, 7, 'Review semanal #1', E'Primeira semana do Nível 2. Sem investir nenhum real ainda, você já entende mais sobre finanças do que 80% dos brasileiros.\n\n**Review semanal #1:**\n1. Sei explicar renda fixa vs variável? Sim / Parcial / Não\n2. Sei o que é CDI, Selic, IPCA? Sim / Parcial / Não\n3. Identifiquei meu perfil de investidor: Conservador / Moderado / Arrojado\n4. Tenho corretora aberta? Sim / Ainda não\n5. Horas de educação financeira essa semana: ___h\n6. Reserva de emergência atual: R$___\n7. Nota de confiança para investir (1-10): ___\n\n**🏆 Badge: "Vocabulário Financeiro" — Semana 1 N2 completa**', true, 15);

  -- DAY 8
  INSERT INTO public.journey_days (journey_id, phase_id, day_number, title, card_content, estimated_minutes) VALUES
  (v_journey_id, v_phase2_id, 8, 'Tesouro Selic: sua primeira aplicação real', E'Hoje você vai fazer seu primeiro investimento REAL fora da poupança. Pode ser com R$30. O valor não importa — o ato de investir importa.\n\n**Tesouro Selic — O que é:**\n- Título público federal (você empresta dinheiro pro governo)\n- Rende a taxa Selic (~15% ao ano)\n- Liquidez diária (pode sacar em D+1)\n- Risco mais baixo do mercado (risco soberano)\n- Investimento mínimo: ~R$30\n- Ideal para: reserva de emergência e dinheiro de curto prazo\n\n**Por que é melhor que poupança:**\n- Poupança: ~8,3%/ano | Tesouro Selic: ~15%/ano bruto (~12,5% líquido)\n- Diferença: ~50% a mais de rendimento com mesmo nível de segurança\n\n**Como investir:**\n1. Acesse sua corretora/banco digital\n2. Busque "Tesouro Selic"\n3. Escolha o vencimento mais distante\n4. Insira o valor (mínimo ~R$30)\n5. Confirme — pronto, você é investidor\n\n**Custos:** Taxa de custódia B3: 0,20%/ano (isenta até R$10.000 no Tesouro Selic). IR: tabela regressiva. IOF: nos primeiros 30 dias.\n\n**AÇÃO:** Invista qualquer valor no Tesouro Selic HOJE.', 20);

  -- DAY 9
  INSERT INTO public.journey_days (journey_id, phase_id, day_number, title, card_content, estimated_minutes) VALUES
  (v_journey_id, v_phase2_id, 9, 'Tesouro IPCA+: proteção contra inflação', E'O Tesouro Selic protege no curto prazo. O Tesouro IPCA+ protege seu poder de compra no LONGO prazo.\n\n**Tesouro IPCA+ — O que é:**\n- Paga IPCA (inflação) + taxa fixa. Ex: IPCA + 7%/ano\n- Garante SEMPRE render acima da inflação (se segurar até o vencimento)\n- Investimento mínimo: ~R$30\n- Vencimentos longos: 2029, 2035, 2045\n\n**Por que é poderoso:**\n- ÚNICO investimento que GARANTE rendimento real\n- Com IPCA+7%, seu dinheiro DOBRA em termos reais a cada ~10 anos\n- Ideal para: aposentadoria, metas de 5+ anos, construção de patrimônio\n\n**ATENÇÃO — Marcação a mercado:**\nSe vender ANTES do vencimento, o preço pode ser menor do que pagou. Acontece quando juros sobem após a compra. Não é perda real se segurar até o vencimento — mas causa pânico.\n\n**Regra de ouro:** Compre Tesouro IPCA+ com dinheiro que NÃO vai precisar antes do vencimento. Precisa de liquidez? Tesouro Selic.\n\n**Alocação até aqui:**\n- Reserva de emergência (3-6 meses) → Tesouro Selic\n- Dinheiro de médio/longo prazo → Tesouro IPCA+', 15);

  -- DAY 10
  INSERT INTO public.journey_days (journey_id, phase_id, day_number, title, card_content, is_cliff_day, estimated_minutes) VALUES
  (v_journey_id, v_phase2_id, 10, 'CDB, LCI e LCA: emprestando para bancos', E'Tesouro Direto é emprestar para o governo. CDB é emprestar para bancos. LCI/LCA são a mesma coisa, mas com benefício fiscal.\n\n**CDB (Certificado de Depósito Bancário):**\n- Você empresta dinheiro para um banco, ele paga juros (% do CDI)\n- Protegido pelo FGC até R$250.000 por CPF por banco\n- Liquidez diária ou no vencimento\n\n**O que buscar:** Liquidez diária + 100% CDI = bom para reserva. CDB de banco médio, 2+ anos: 120-130% CDI.\n\n**LCI e LCA:**\n- Mesma lógica do CDB, mas com ISENÇÃO DE IR para pessoa física\n- LCI = Letra de Crédito Imobiliário | LCA = Letra de Crédito do Agronegócio\n- LCI/LCA de 85% CDI ≈ CDB de ~100% CDI (por não ter IR)\n\n**Comparação prática (R$10.000, 1 ano, CDI a 15%):**\n- Poupança: ~R$830 líquido\n- CDB 100% CDI: ~R$1.237 líquido (após IR 17,5%)\n- LCI 90% CDI: ~R$1.350 líquido (isento IR)\n- Tesouro Selic: ~R$1.237 líquido\n\n**Onde encontrar bons CDBs:** Corretoras independentes (XP, Rico, BTG) oferecem CDBs de diversos bancos com taxas melhores que seu próprio banco.', true, 20);

  -- DAY 11
  INSERT INTO public.journey_days (journey_id, phase_id, day_number, title, card_content, is_cliff_day, estimated_minutes) VALUES
  (v_journey_id, v_phase2_id, 11, 'Montando sua base de renda fixa', E'Chega de teoria. Hoje vamos montar sua alocação de renda fixa — a base que dá segurança para tudo que vem depois.\n\n**Alocação de renda fixa (modelo para iniciantes):**\n\n| Propósito | Produto | % da renda fixa | Liquidez |\n|-----------|---------|-----------------|----------|\n| Reserva de emergência | Tesouro Selic ou CDB DI 100% CDI | 40-50% | Diária |\n| Proteção contra inflação | Tesouro IPCA+ (vencimento 2035+) | 30-40% | No vencimento |\n| Oportunidade de renda | CDB/LCI/LCA de bancos médios | 10-20% | Variada |\n\n**Exemplo com R$5.000:**\n- R$2.500 → Tesouro Selic (reserva)\n- R$1.500 → Tesouro IPCA+ 2035 (longo prazo)\n- R$1.000 → CDB 120% CDI, 2 anos\n\n**Se tem menos de R$5.000:** Comece 100% em Tesouro Selic até completar a reserva. Depois diversifique.\n\n**Ação de hoje:** Defina quanto alocar em cada categoria:\n- Tesouro Selic: R$___\n- Tesouro IPCA+: R$___\n- CDB/LCI/LCA: R$___', true, 20);

  -- DAY 12
  INSERT INTO public.journey_days (journey_id, phase_id, day_number, title, card_content, is_cliff_day, estimated_minutes) VALUES
  (v_journey_id, v_phase2_id, 12, 'Check de carteira: veja sem reagir', E'Agora que você tem investimentos, mora um perigo: acompanhar demais. Quem checa todo dia toma decisões piores que quem checa 1x/semana.\n\n**NOVO HÁBITO — Check semanal de carteira:**\n1x por semana (máximo), abra a corretora e veja:\n- Saldo total investido: R$___\n- Rendimento acumulado: R$___\n- Algum vencimento próximo? Sim / Não\n\n**As 3 regras do check:**\n1. **VEJA** o saldo\n2. **ANOTE** no dashboard\n3. **NÃO FAÇA NADA** (a menos que seja dia de aporte programado)\n\nInvestimento de longo prazo não precisa de ação semanal. A ansiedade de "preciso fazer alguma coisa" é viés comportamental que destrói retornos.\n\n**A ciência:** Investidores em fundos de índice reduzem frequência de trades em 40% e obtêm retornos melhores. Menos ação = mais retorno. Contraintuitivo, mas comprovado.', true, 10);

  -- DAY 13
  INSERT INTO public.journey_days (journey_id, phase_id, day_number, title, card_content, is_rest_day, is_cliff_day, motivational_note, estimated_minutes) VALUES
  (v_journey_id, v_phase2_id, 13, 'THE CLIFF do Nível 2', E'Se você está pensando "isso é complicado demais" ou "vou começar a investir mês que vem quando entender melhor" — parabéns, você encontrou o CLIFF do Nível 2.\n\n**O CLIFF do investimento:**\n- "Preciso estudar mais antes de começar" → Sabe o que é Tesouro Selic? Invista R$30 e aprenda fazendo\n- "Vou esperar a Selic baixar / o mercado melhorar" → Quem espera o momento perfeito nunca investe\n- "Tenho pouco dinheiro, não faz diferença" → R$100/mês dos 22 aos 62 a 12%/ano = ~R$1 milhão\n- "Investimento é coisa de rico" → Tesouro Direto começa com R$30, ETF com R$10\n\n**O antídoto é ação imperfeita:**\nNão espere entender tudo. Invista R$30 no Tesouro Selic HOJE e aprenda com o dinheiro trabalhando.\n\n**Mínimo inegociável:**\n1. Ter pelo menos R$30 investidos em Tesouro Selic\n2. 15 min de educação financeira\n3. Manter orçamento e automação rodando', true, true, 'Se acha complicado demais, é porque está aprendendo. R$30 no Tesouro Selic já te coloca à frente de quem ficou na teoria. Continue.', 10);

  -- DAY 14
  INSERT INTO public.journey_days (journey_id, phase_id, day_number, title, card_content, is_review_day, estimated_minutes) VALUES
  (v_journey_id, v_phase2_id, 14, 'Review semanal #2', E'Duas semanas do Nível 2. Você já tem dinheiro investido fora da poupança, entende renda fixa e sabe mais que a maioria.\n\n**Review semanal #2:**\n1. Total investido em renda fixa: R$___\n2. Onde: Tesouro Selic R$___ / IPCA+ R$___ / CDB R$___ / Outro R$___\n3. Migrei dinheiro da poupança? Sim R$___ / Não\n4. Horas de educação financeira essa semana: ___h\n5. Fiz check de carteira sem reagir emocionalmente? Sim / Não\n6. Nota de confiança sobre renda fixa (1-10): ___\n\n**🏆 Badge: "Primeiro Investimento" — Semana 2 N2 completa**', true, 15);

  -- DAY 15
  INSERT INTO public.journey_days (journey_id, phase_id, day_number, title, card_content, estimated_minutes) VALUES
  (v_journey_id, v_phase3_id, 15, 'ETFs: o investimento mais inteligente para iniciantes', E'Se eu pudesse recomendar UM tipo de investimento em renda variável para iniciantes, seria ETF.\n\n**NOVO HÁBITO — Review mensal de carteira:**\n1x por mês, faça análise completa: composição, rendimento, rebalanceamento.\n\n**ETF — Por que é perfeito para iniciantes:**\n- Diversificação automática: 1 cota de BOVA11 = ~80 maiores empresas BR\n- Custo baixo: taxa de adm de 0,10-0,30%/ano (vs 1-2% de fundos ativos)\n- Sem stock picking: o índice faz o trabalho\n- Performance: investimento passivo supera a maioria dos gestores ativos\n\n**4 ETFs essenciais:**\n- BOVA11 (Ibovespa) — ~80 maiores empresas BR. Taxa 0,10%. ~R$130/cota.\n- IVVB11 (S&P 500) — 500 maiores dos EUA + proteção cambial. Taxa 0,23%. ~R$400/cota.\n- SMAL11 (Small Cap) — Empresas menores BR. Taxa 0,50%. ~R$100/cota.\n- B5P211 (IMA-B 5+) — Títulos IPCA+ longos. Taxa 0,20%. ~R$25/cota.\n\n**Para começar:** BOVA11 + IVVB11 cobrem as maiores empresas do mundo com 2 ativos.\n\n**Como comprar:** Home broker da corretora → busque o código → quantidade → Comprar.\n\n**IR em ETFs:** 15% sobre ganho na venda. SEM isenção de R$20k/mês. Recolher via DARF.', 20);

  -- DAY 16
  INSERT INTO public.journey_days (journey_id, phase_id, day_number, title, card_content, estimated_minutes) VALUES
  (v_journey_id, v_phase3_id, 16, 'Fundos Imobiliários (FIIs): renda passiva mensal', E'FIIs são como ser "dono de imóvel" sem comprar imóvel. Você recebe aluguéis mensais na conta — isentos de IR.\n\n**FIIs — O que são:**\n- Fundos que investem em imóveis ou títulos imobiliários\n- Negociados na bolsa como ações\n- Distribuem rendimentos mensais (como "aluguel")\n- Rendimentos isentos de IR para pessoa física\n- Cota mínima: ~R$10-100\n\n**Tipos de FIIs:**\n- **Tijolo:** Imóveis reais (shoppings, galpões, escritórios)\n- **Papel:** Títulos de crédito imobiliário (CRIs, LCIs). Rendimentos maiores com Selic alta\n- **FOFs (Fundo de Fundos):** Investem em outros FIIs — diversificação automática\n\n**Vantagens:** Renda mensal isenta, acessível (cotas a partir de R$10), sem administrar imóvel, liquidez na bolsa.\n\n**Cuidados:** Cota pode desvalorizar, dividend yield alto nem sempre = bom fundo, IR de 20% sobre ganho de capital na venda.\n\n**Exemplo de renda passiva:**\n- R$10.000 com yield de 1%/mês = R$100/mês isento\n- R$50.000 = R$500/mês | R$100.000 = R$1.000/mês\n- Reinvestir rendimentos + aportes = efeito bola de neve', 15);

  -- DAY 17
  INSERT INTO public.journey_days (journey_id, phase_id, day_number, title, card_content, estimated_minutes) VALUES
  (v_journey_id, v_phase3_id, 17, 'Ações: introdução sem obrigação', E'Ações são o investimento mais popular e o mais incompreendido. NÃO é cassino, NÃO é loteria, e NÃO é obrigatório agora.\n\n**Ações — O básico:**\n- Comprar uma ação = virar SÓCIO da empresa\n- Empresa cresce e lucra → ação tende a valorizar\n- Algumas pagam dividendos (parte do lucro aos acionistas)\n- Alto potencial de retorno + alta volatilidade\n\n**Critérios básicos (se quiser comprar depois dos ETFs):**\n- Empresa lucrativa (lucro líquido positivo e crescente)\n- Boa gestão (governança corporativa)\n- Setor que você entende\n- Baixo endividamento\n- Paga dividendos consistentemente\n\n**O que NÃO fazer:**\n- Comprar porque "o cara do YouTube falou"\n- Day trade (97% perdem — estudo FGV)\n- Investir tudo em 1-2 ações\n- Vender em pânico quando cai\n- Comprar ações que não entende\n\n**Recomendação para N2:** NÃO se preocupe com ações individuais agora. ETFs já dão exposição diversificada com menos risco.', 15);

  -- DAY 18
  INSERT INTO public.journey_days (journey_id, phase_id, day_number, title, card_content, estimated_minutes) VALUES
  (v_journey_id, v_phase3_id, 18, 'Sua primeira carteira diversificada', E'Hoje é o dia de montar sua carteira. Simples, diversificada, e poderosa para construir patrimônio por décadas.\n\n**Carteira Iniciante Moderada:**\n- Tesouro Selic: 30% (reserva + liquidez)\n- Tesouro IPCA+: 25% (proteção contra inflação)\n- CDB/LCI/LCA: 15% (renda fixa com retorno extra)\n- BOVA11: 15% (exposição a empresas BR)\n- IVVB11: 15% (exposição internacional + câmbio)\n\n**Carteira Iniciante Moderada-Arrojada:**\n- Tesouro Selic: 20% | Tesouro IPCA+: 20% | CDB/LCI/LCA: 10%\n- BOVA11: 20% | IVVB11: 20% | FIIs: 10%\n\n**Monte SUA carteira:**\n- Tesouro Selic: ___% = R$___\n- Tesouro IPCA+: ___% = R$___\n- CDB/LCI/LCA: ___% = R$___\n- BOVA11: ___% = R$___\n- IVVB11: ___% = R$___\n- FIIs: ___% = R$___\n- TOTAL: 100% = R$___\n\nEssa alocação vai evoluir. Não precisa ser perfeita agora. Precisa EXISTIR.', 20);

  -- DAY 19
  INSERT INTO public.journey_days (journey_id, phase_id, day_number, title, card_content, estimated_minutes) VALUES
  (v_journey_id, v_phase3_id, 19, 'DCA: o método anti-pânico', E'O maior medo de quem investe em renda variável: "e se eu investir HOJE e cair AMANHÃ?" A resposta é DCA (Dollar Cost Averaging).\n\n**Como funciona:**\nInvista valor FIXO todo mês, independente do mercado:\n- Mês 1: BOVA11 a R$130/cota → compra 1\n- Mês 2: BOVA11 a R$110/cota → compra 1 (em promoção)\n- Mês 3: BOVA11 a R$140/cota → compra 1\n- Preço médio: R$126,67 por cota\n\nVocê compra MAIS cotas quando está barato e MENOS quando caro, automaticamente.\n\n**Por que funciona:**\n- Remove emoção ("será que é o momento certo?")\n- Elimina risco de comprar tudo no topo\n- Cria consistência — hábito importa mais que timing\n- Psicologicamente confortável\n\n**Na prática (dia do pagamento):**\n1. Automação paga a reserva (Tesouro Selic)\n2. Valor definido vai para ETFs\n3. Você não olha o preço, não espera o "momento certo"\n\n**Quanto em renda variável:** Dos 20% da renda investidos, divida: 50-60% renda fixa + 40-50% renda variável. Ajuste conforme perfil.', 15);

  -- DAY 20
  INSERT INTO public.journey_days (journey_id, phase_id, day_number, title, card_content, estimated_minutes) VALUES
  (v_journey_id, v_phase3_id, 20, 'Renda extra: o turbo da carteira', E'Otimizar gastos e investir bem é metade da equação. A outra metade: GANHAR MAIS.\n\n**NOVO HÁBITO — Renda extra ativa:**\nDedique 30-60 min/dia (ou 3-5h/semana) a construir fonte de renda extra.\n\n**Os 3 caminhos:**\n\n**1. Freelance / Serviço:** Monetize habilidade existente — marketing digital, design, programação, escrita, edição de vídeo, Excel. Plataformas: Workana, 99Freelas, Fiverr, GetNinjas.\n\n**2. Produto digital:** Crie uma vez, venda infinitas: e-book, template (Notion, Excel, Canva), mini-curso, automação. Plataformas: Hotmart, Kiwify, Gumroad.\n\n**3. Venda / Revenda:** Itens usados (OLX, Enjoei, Mercado Livre), revenda com margem, importação pequena escala.\n\n**A regra de ouro:** 100% da renda extra vai para investimentos. NÃO para aumentar padrão de vida. Renda extra = combustível do patrimônio.\n\n**Exercício:**\n- Minha habilidade mais monetizável: ___\n- Primeiro passo para oferecer: ___\n- Meta de renda extra este mês: R$___', 15);

  -- DAY 21
  INSERT INTO public.journey_days (journey_id, phase_id, day_number, title, card_content, is_review_day, estimated_minutes) VALUES
  (v_journey_id, v_phase3_id, 21, 'Review semanal #3', E'Três semanas. Você tem renda fixa + renda variável na carteira. Sabe a diferença entre Tesouro Selic e IPCA+, entre ETF e ação. Isso é mais do que 90% dos seus amigos.\n\n**Review semanal #3:**\n1. Composição da carteira:\n   - Renda fixa: R$___ (___%%)\n   - Renda variável: R$___ (___%%)\n2. Fiz aporte essa semana? R$___\n3. Check de carteira: saldo subiu/desceu? Como me senti?\n4. Horas de educação financeira: ___h\n5. Renda extra: fiz alguma ação concreta? Sim / Não\n6. Nota de confiança investindo (1-10): ___\n\n**🏆 Badge: "Carteira Montada" — Semana 3 N2 completa**', true, 15);

  -- DAY 22
  INSERT INTO public.journey_days (journey_id, phase_id, day_number, title, card_content, estimated_minutes) VALUES
  (v_journey_id, v_phase4_id, 22, 'Automação total: aportes no piloto automático', E'No Nível 1, automatizamos a poupança. Agora vamos automatizar os INVESTIMENTOS.\n\n**Seu sistema de automação completo:**\n\n**Dia do pagamento (D+0 ou D+1):**\n1. Transferência automática: ___% da renda → conta da corretora\n2. Débito automático: contas fixas\n3. O que sobra = gastos variáveis do mês\n\n**Dia de aporte (D+2 ou D+3):**\n1. Investir em renda fixa (Tesouro Selic/IPCA+/CDB)\n2. Comprar ETFs (BOVA11, IVVB11)\n3. Aportar em FIIs (se na carteira)\n\n**Corretoras com aporte programado:**\n- Nubank: investimento programado em renda fixa\n- XP/Rico: Tesouro Direto com agendamento\n- Clear: sem taxa para ETFs\n\n**Se não puder automatizar 100%:** Lembrete mensal no celular: "DIA DE APORTE" — execute em 10 minutos.\n\n**A meta:** Nos dias bons e ruins, motivado ou não, o sistema roda igual. Automação garante consistência — não a motivação.', 20);

  -- DAY 23
  INSERT INTO public.journey_days (journey_id, phase_id, day_number, title, card_content, estimated_minutes) VALUES
  (v_journey_id, v_phase4_id, 23, 'Rebalanceamento: mantenha a máquina ajustada', E'Com o tempo, sua carteira sai do equilíbrio. Se ações subiram muito, passam a representar mais % do que deviam. Rebalancear = trazer de volta ao plano original.\n\n**O que é rebalanceamento:**\nMeta: 60% renda fixa + 40% variável. Após 6 meses, ações subiram: agora é 50/50. Rebalancear: direcionar novos aportes para renda fixa até voltar a 60/40.\n\n**Para iniciantes — Método simples:**\nEm vez de vender e recomprar, use os novos aportes:\n- Renda variável passou da meta → aporte vai mais para renda fixa\n- Renda fixa passou da meta → aporte vai mais para renda variável\n\n**Frequência:** A cada 3-6 meses. NÃO toda semana. NÃO todo mês.\n\n**Quando rebalancear de verdade:**\n- Desvio > 5% da meta original\n- Mudança significativa no seu perfil/objetivos\n- Novo ciclo de aporte trimestral', 15);

  -- DAY 24
  INSERT INTO public.journey_days (journey_id, phase_id, day_number, title, card_content, estimated_minutes) VALUES
  (v_journey_id, v_phase4_id, 24, 'Proteção: seguros e previdência', E'Investir é ofensa. Proteção é defesa. Sem defesa, um único imprevisto pode zerar todo o trabalho.\n\n**O que proteger (em ordem):**\n\n**1. Reserva de emergência (já tem!):** 3-6 meses em Tesouro Selic.\n\n**2. Seguro de vida (se tem dependentes):** Custo: R$30-80/mês para jovem saudável.\n\n**3. Previdência privada (PGBL ou VGBL):**\n- PGBL: Deduz até 12% da renda bruta do IR. Bom para declaração completa.\n- VGBL: IR só sobre rendimentos no resgate. Bom para declaração simplificada.\n- ATENÇÃO: Muitos fundos têm taxas de 2-3%/ano. Só vale com taxa < 1% e benefício fiscal.\n\n**Para 20-25 anos:** Previdência NÃO é prioridade. ETFs + Tesouro IPCA+ fazem melhor com menos taxas. Considere só se:\n- Faz declaração completa (PGBL com dedução)\n- Encontra fundo com taxa < 0,5%/ano\n- Quer disciplina forçada', 15);

  -- DAY 25
  INSERT INTO public.journey_days (journey_id, phase_id, day_number, title, card_content, estimated_minutes) VALUES
  (v_journey_id, v_phase4_id, 25, 'Armadilhas: o que evitar a todo custo', E'Saber o que NÃO fazer é tão importante quanto saber o que fazer.\n\n**10 armadilhas mais comuns para jovens investidores:**\n\n1. **Day trade como renda** — 97% perdem dinheiro (estudo FGV). Não é investimento, é cassino.\n2. **Seguir gurus cegamente** — Muitos ganham vendendo cursos, não investindo. Desconfie de retornos garantidos.\n3. **Tudo em uma coisa** — 100% cripto, 100% em 1 ação. Diversificação é proteção.\n4. **Vender no pânico** — Queda de 20%? Se vender, transforma oscilação em perda permanente.\n5. **Comprar no hype** — FOMO = receita para comprar caro e vender barato.\n6. **Ignorar taxas** — Fundo ativo de 2%/ano: em 20 anos, taxas comem ~33% do retorno.\n7. **Cripto como base** — Pode ser 5-10% da carteira. Nunca a fundação.\n8. **Comprar só porque caiu** — Às vezes caiu porque a empresa está quebrando.\n9. **Não declarar IR** — ETFs, ações e FIIs precisam ser declarados. DARF obrigatório.\n10. **Procrastinar** — A armadilha mais cara. Cada mês de atraso é dinheiro que não volta.', 15);

  -- DAY 26
  INSERT INTO public.journey_days (journey_id, phase_id, day_number, title, card_content, estimated_minutes) VALUES
  (v_journey_id, v_phase4_id, 26, 'Imposto de renda para investidores', E'Ninguém gosta de IR. Mas ignorar pode custar caro em multas e pagar mais do que deveria.\n\n**IR por tipo de investimento:**\n- Tesouro Direto: tabela regressiva (22,5%→15%) — retido na fonte\n- CDB: tabela regressiva — retido na fonte\n- LCI/LCA: ISENTO para PF\n- ETFs: 15% sobre ganho na venda — você recolhe via DARF\n- Ações: 15% sobre ganho (isenção até R$20k/mês) — você recolhe via DARF\n- FIIs rendimentos: ISENTO para PF\n- FIIs ganho de capital: 20% na venda — você recolhe via DARF\n\n**O que saber AGORA:**\n1. Renda fixa: IR descontado automaticamente. Nada a fazer.\n2. ETFs e ações: vendeu com lucro → DARF até último dia útil do mês seguinte.\n3. FIIs: rendimentos isentos, ganho na venda não.\n4. Use app para controlar (MyProfit, Kinvo, Gorila).\n\n**Declaração anual:** Todo abril-maio, declare investimentos. Posição em 31/12 precisa ser declarada mesmo sem venda. Sua corretora fornece informe de rendimentos.', 15);

  -- DAY 27
  INSERT INTO public.journey_days (journey_id, phase_id, day_number, title, card_content, estimated_minutes) VALUES
  (v_journey_id, v_phase4_id, 27, 'Net worth: quanto você vale?', E'Seu patrimônio líquido (net worth) é o número mais importante das suas finanças. Não é quanto você ganha — é quanto você TEM.\n\n**Como calcular:**\n\n**ATIVOS (o que você tem):**\n- Investimentos (renda fixa + variável): R$___\n- Saldo em conta: R$___\n- Valor de bens (carro, eletrônicos): R$___\n- Total de ativos: R$___\n\n**PASSIVOS (o que você deve):**\n- Dívidas de cartão: R$___\n- Empréstimos: R$___\n- Parcelas restantes: R$___\n- Total de passivos: R$___\n\n**PATRIMÔNIO LÍQUIDO = Ativos - Passivos = R$___**\n\nSe for negativo: não entre em pânico. Muitos jovens de 20-25 têm patrimônio negativo. O que importa é a TRAJETÓRIA — está crescendo mês a mês?\n\n**Acompanhe mensalmente:** Registre patrimônio líquido todo mês. O gráfico crescendo é a prova visual de que o sistema funciona.', 15);

  -- DAY 28
  INSERT INTO public.journey_days (journey_id, phase_id, day_number, title, card_content, is_review_day, estimated_minutes) VALUES
  (v_journey_id, v_phase4_id, 28, 'Review semanal #4 + Review mensal', E'Última semana. Hora do review mais completo.\n\n**Review semanal #4:**\n1. Total investido (toda a carteira): R$___\n2. Composição: Renda fixa ___% / Renda variável ___%\n3. Patrimônio líquido: R$___\n4. Aporte total do mês: R$___\n\n**Review mensal completo:**\n1. Rendimento total do mês: R$___\n2. Rebalanceamento necessário? Sim / Não\n3. Alguma armadilha que quase caí? ___\n4. Renda extra gerada: R$___\n5. Educação financeira total do mês: ___h\n6. Metas para o próximo mês: ___', true, 20);

  -- DAY 29
  INSERT INTO public.journey_days (journey_id, phase_id, day_number, title, card_content, estimated_minutes) VALUES
  (v_journey_id, v_phase4_id, 29, 'Seu protocolo financeiro completo', E'Do Nível 1 ao Nível 2, você construiu um sistema financeiro completo. Hoje definimos o protocolo permanente.\n\n**Protocolo permanente — Sistema completo:**\n\n**DIÁRIO (5 min):**\n- [ ] Registrar gastos principais\n- [ ] Pausa consciente antes de compras\n- [ ] 15 min de educação financeira\n\n**SEMANAL (15 min):**\n- [ ] Review financeiro (gastos da semana)\n- [ ] Check de carteira (sem reagir)\n- [ ] Orçamento da próxima semana\n\n**MENSAL (30 min):**\n- [ ] Pague-se primeiro (automático)\n- [ ] Aporte em investimentos (automático ou manual)\n- [ ] Review completo da carteira\n- [ ] Calcular patrimônio líquido\n- [ ] Recolher DARF se vendeu com lucro\n\n**TRIMESTRAL (1 hora):**\n- [ ] Rebalancear carteira se necessário\n- [ ] Auditoria de assinaturas\n- [ ] Renegociar gastos fixos\n- [ ] Avaliar se % de poupança pode subir\n\n**ANUAL (2 horas):**\n- [ ] Declaração de IR\n- [ ] Revisão de metas financeiras\n- [ ] Avaliar perfil de investidor\n- [ ] Planejar próximo ano', 15);

  -- DAY 30
  INSERT INTO public.journey_days (journey_id, phase_id, day_number, title, card_content, estimated_minutes) VALUES
  (v_journey_id, v_phase4_id, 30, 'GRADUAÇÃO: Faça Seu Dinheiro Trabalhar', E'60 dias de transformação financeira. De zero controle no Dia 1 do Nível 1 para um sistema completo de controle, investimento e construção de patrimônio.\n\n**Transformação completa (N1 + N2):**\n\n| Métrica | Início N1 | Fim N1 | Fim N2 |\n|---------|-----------|--------|--------|\n| Controle financeiro (1-10) | ___ | ___ | ___ |\n| Tem orçamento? | Não | Sim | Sim + investimentos |\n| Reserva de emergência | R$0 | R$___ | R$___ |\n| Total investido | R$0 | R$___ | R$___ |\n| Patrimônio líquido | R$___ | R$___ | R$___ |\n| Entende renda fixa? | Não | Básico | Sim |\n| Entende renda variável? | Não | Não | Sim |\n| Carteira diversificada? | Não | Não | Sim |\n| Automação? | Não | Poupança | Poupança + Investimentos |\n| Fontes de renda | 1 | 1 | 1 + extra planejada |\n\n**O que você construiu:**\n- Sistema de controle de gastos e orçamento\n- Automação de poupança E investimentos\n- Reserva em produto inteligente (Tesouro Selic)\n- Carteira diversificada: renda fixa + variável + exposição internacional\n- Método DCA de aportes mensais\n- Entendimento de IR, taxas e armadilhas\n- Protocolo de review diário/semanal/mensal/trimestral/anual\n\n**Marcos de longo prazo:**\n- [ ] Reserva: 3 meses → 6 meses\n- [ ] R$10.000 → R$50.000 → R$100.000 investidos\n- [ ] Renda passiva: R$100/mês → R$500/mês → R$1.000/mês\n- [ ] Independência financeira (renda passiva > despesas)\n\n**🏆 Badge Final: "Dinheiro Trabalhando" — Nível 2 completo**\n**🔓 Jornada "Assuma Suas Finanças" COMPLETA (N1 + N2)**', 15);

  -- ============================================
  -- 3. Habit Templates
  -- ============================================

  INSERT INTO public.journey_habit_templates (journey_id, name, emoji, category, period, tracking_type, unit, initial_goal_value, start_day, end_day, frequency_type, days_of_week, goal_progression, canonical_key, sort_order) VALUES

  -- 1. Educação financeira diária (Day 3 → end, daily, checkbox, 15 min/dia)
  (v_journey_id, 'Educação financeira diária', '📰', 'finanças', 'morning', 'checkbox', 'none', NULL, 3, NULL, 'daily', '{0,1,2,3,4,5,6}', '[]', 'financial_education', 1),

  -- 2. Aporte mensal (Day 5 → end, number, custom, R$)
  (v_journey_id, 'Aporte mensal', '📈', 'finanças', 'morning', 'number', 'custom', NULL, 5, NULL, 'daily', '{0,1,2,3,4,5,6}', '[]', 'monthly_investment', 2),

  -- 3. Check de carteira (Day 12 → end, weekly Sunday, checkbox)
  (v_journey_id, 'Check de carteira', '🧊', 'finanças', 'evening', 'checkbox', 'none', NULL, 12, NULL, 'weekly', '{0}', '[]', 'portfolio_check', 3),

  -- 4. Review mensal de carteira (Day 15 → end, checkbox)
  (v_journey_id, 'Review mensal de carteira', '📊', 'finanças', 'evening', 'checkbox', 'none', NULL, 15, NULL, 'daily', '{0,1,2,3,4,5,6}', '[]', 'monthly_portfolio_review', 4),

  -- 5. Renda extra ativa (Day 20 → end, checkbox)
  (v_journey_id, 'Renda extra ativa', '💡', 'finanças', 'evening', 'checkbox', 'none', NULL, 20, NULL, 'daily', '{0,1,2,3,4,5,6}', '[]', 'extra_income', 5),

  -- 6. Review semanal (Day 7 → end, weekly Sunday, checkbox)
  (v_journey_id, 'Review semanal', '📋', 'finanças', 'evening', 'checkbox', 'none', NULL, 7, NULL, 'weekly', '{0}', '[]', 'weekly_review_finances', 6);

END $$;
